/* burrowing-animals.js
 * 38 burrowing animals organized by phylogenetic group.
 * Each carries an operational-signature writeup in bookwormburrows-pedagogy register.
 * Worm canonical at #1. Cats absent (cats are occupiers, not burrowers).
 */

(function(global) {
  'use strict';

  var ANIMALS = [
    // INVERTEBRATES (12)
    { slug:'earthworm', name:'Earthworm', group:'invertebrate', writeup:"The canonical bookwormburrows ancestor. The earthworm eats text in its substrate-form (decaying plant matter) and excretes the soil that gardens grow in. Operates entirely within the burrow; never emerges except by accident or under duress. Carries themes of: digestion as primary mode of knowing, rich nutrient-density of the underground, refusal of surface-spectacle. The figure who turns what is dead into what is alive without ever needing to be seen doing it." },
    { slug:'wolf-spider', name:'Wolf spider', group:'invertebrate', writeup:"Wolf spiders dig vertical tube-burrows and hunt from the entrance — the figure who waits in their own threshold. Excellent eyesight (rare among spiders), carries her young on her back. The wolf spider character is the ambush-intelligence that watches more than acts, with a fierce mothering layer underneath the predator-posture. Carries themes of: patience as method, the threshold-position, the parent who is also the warrior." },
    { slug:'tarantula', name:'Tarantula', group:'invertebrate', writeup:"Tarantulas dig deep silk-lined burrows and emerge slowly, often only at night. Long-lived (some females live 30+ years), they are the elder-spider of their territory. Carries themes of: longevity, slow metabolism as wisdom, the figure whose deep burrow is a personal cosmos developed across decades. The misunderstood predator — most tarantulas are harmless to humans despite the iconography." },
    { slug:'trapdoor-spider', name:'Trapdoor spider', group:'invertebrate', writeup:"Trapdoor spiders construct a hinged camouflaged door over their burrow and ambush prey that triggers silk threads radiating from the entrance. The figure whose entire architecture is a single lure-and-strike system. Carries themes of: precision-design, patience operationalized into infrastructure, the figure whose home IS their hunting method. The architectural intelligence that builds the trap and waits." },
    { slug:'mole-cricket', name:'Mole cricket', group:'invertebrate', writeup:"Mole crickets dig with shovel-like forelimbs and sing from acoustically-tuned burrow-chambers — the burrow itself is the instrument that amplifies their call. Carries themes of: the burrow as broadcasting device, music as territorial declaration, the figure whose underground voice carries across surface distance. The artist who builds their own concert hall." },
    { slug:'cicada-nymph', name:'Cicada nymph', group:'invertebrate', writeup:"Cicada nymphs live underground for years (periodical cicadas: 13 or 17 years) before emerging for a brief adult phase of singing, mating, dying. Carries themes of: the long preparation, dramatic emergence after invisible decades, the figure whose surface-life is the smallest fraction of their actual life. Most of the existence happens in the burrow; the burst above is just the punctuation." },
    { slug:'carpenter-ant', name:'Carpenter ant', group:'invertebrate', writeup:"Carpenter ants don't eat the wood they tunnel — they excavate galleries to live in, leaving the structural material for someone else's purposes. Carries themes of: collective-architectural intelligence, the figure who shapes infrastructure for the colony rather than for personal gain, distributed cognition. The worker whose individual contribution disappears into the nest's emergent intelligence." },
    { slug:'termite', name:'Termite', group:'invertebrate', writeup:"Termite mounds reach 8 meters tall and 8 meters down, climate-controlled with passive ventilation systems that have inspired human architects (the Eastgate Centre in Harare). Eusocial, with castes — workers, soldiers, reproductives — coordinating at colony scale. Carries themes of: monumental collective construction, climate-engineering intelligence, the figure who builds for the colony's centuries rather than the individual's seasons. Architecture as species-level intelligence." },
    { slug:'mason-bee', name:'Mason bee', group:'invertebrate', writeup:"Solitary bees that nest in pre-existing tubes — hollow stems, woodpecker holes, paper tubes — sealing their eggs in chambers separated by mud walls. The figure who finds a tube and fills it with carefully-prepared next-generation. Carries themes of: solitary excellence, the gentle pollinator, preparation for futures one will not see. Solitary but not lonely — adjacent to other mason bees, just not nesting communally." },
    { slug:'dung-beetle', name:'Dung beetle', group:'invertebrate', writeup:"Dung beetles roll dung to underground burrows, using it as food and breeding chamber. Some species navigate by the Milky Way — the dung beetle is the only insect known to use stellar orientation. Carries themes of: turning waste into substrate-of-the-next-generation, cosmic navigation while doing the lowly work, the figure whose dirty job is also their stargazing. Nothing is beneath them; they are literally beneath everything." },
    { slug:'fiddler-crab', name:'Fiddler crab', group:'invertebrate', writeup:"Fiddler crabs dig vertical burrows in mudflats, plug them at high tide, emerge at low tide for the asymmetric-clawed mating display. The males' enlarged claw is for ritual combat and signaling, not feeding. Carries themes of: tidal patience, the burrow as escape-hatch from the rhythm of the larger element, asymmetric specialization, the figure whose oversized weapon is also their dance-prop." },
    { slug:'mantis-shrimp', name:'Mantis shrimp', group:'invertebrate', writeup:"Mantis shrimp construct U-shaped burrows in seabed sand and possess the most complex visual system known (16 photoreceptor types vs human 3). Their strike-claws move so fast they create cavitation bubbles. Carries themes of: extreme perceptual range, devastating focused force, the figure whose senses operate on registers others cannot access. The unassuming burrower with hidden capacities." },

    // REPTILES (4)
    { slug:'sand-boa', name:'Sand boa (burrowing snake)', group:'reptile', writeup:"Sand boas spend most of their lives buried with only eyes and nostrils above the substrate, ambushing prey that passes overhead. Carries themes of: complete environmental integration, ambush-intelligence at maximum patience, the figure who has dissolved into the substrate they hunt from. The constrictor whose first move is invisible because the figure already was." },
    { slug:'pygmy-blue-tongue-skink', name:'Pygmy blue-tongue skink', group:'reptile', writeup:"Australian skink that lives almost exclusively in abandoned spider burrows and famously fights from inside — rivals attack each other through the burrow opening, biting heads. Carries themes of: defensive territoriality, fighting from the threshold, opportunistic occupancy of others' work. The figure who didn't dig the home but will absolutely defend it." },
    { slug:'gopher-tortoise', name:'Gopher tortoise', group:'reptile', writeup:"Keystone species in the southeastern US — gopher tortoise burrows shelter over 350 other species during fires, droughts, and freezes. The single tortoise's burrow is a public-utility for an entire ecosystem. Carries themes of: solitary work that benefits multitudes, longevity (60+ years), the figure whose private home is everyone's refuge. Architecture as inadvertent generosity." },
    { slug:'burrowing-skink', name:'Burrowing skink', group:'reptile', writeup:"Many skink species are burrowers with reduced limbs — some functionally limbless, swimming through sand. Smooth-scaled, often with reduced eyes (vision is unhelpful underground). Carries themes of: streamlined being, the figure who has shed external features for greater internal efficiency, the smooth-passage. The body designed for the medium." },

    // AMPHIBIANS (2)
    { slug:'spadefoot-toad', name:'Spadefoot toad', group:'amphibian', writeup:"Spadefoot toads burrow rapidly with hind-foot 'spades' and estivate underground for months or years until heavy rain triggers emergence. They breed in temporary pools, with tadpoles that develop in days. Carries themes of: dormancy as primary mode, explosive responsiveness when conditions arrive, the figure whose long invisibility ends in rapid intense activity. The patient artist whose moment is rare and short." },
    { slug:'caecilian', name:'Caecilian', group:'amphibian', writeup:"Limbless burrowing amphibians, almost-blind, reaching the size of large snakes — most people don't know they exist. Live entirely underground in tropical regions. Carries themes of: total commitment to the underground vocation, the figure who is so specialized their existence is practically secret, knowledge available only to those who go looking. The master practitioner outside any audience." },

    // FISH (1)
    { slug:'lungfish', name:'West African lungfish', group:'fish', writeup:"During the dry season, the West African lungfish burrows into mud, encases itself in a mucus cocoon, and breathes air through a primitive lung — surviving for months until rains return. Phylogenetically closer to land vertebrates than to most other fish. Carries themes of: liminal being, surviving conditions impossible for one's category, the figure who carries the bridge between two evolutionary worlds. Sealed sleep as method." },

    // BIRDS (3)
    { slug:'burrowing-owl', name:'Burrowing owl', group:'bird', writeup:"Small owls that nest in burrows abandoned by prairie dogs, ground squirrels, or armadillos — and modify them to suit. Diurnal, often seen standing at burrow entrances at dawn and dusk. Carries themes of: opportunistic occupancy intelligently improved, the figure who inhabits inherited spaces with their own additions, comfort with twilight registers. The bird-of-wisdom who lives below ground level." },
    { slug:'puffin', name:'Atlantic puffin', group:'bird', writeup:"Puffins dig burrows in cliff-top turf with their beaks and feet, spending months at sea then returning to the same burrow each breeding season. Pair-bond often for life. Carries themes of: oceanic distance held with terrestrial fidelity, the figure who travels far but always comes home, monogamous patience. The colorful figure whose colorfulness is reserved for the few weeks of breeding." },
    { slug:'magellanic-penguin', name:'Magellanic penguin', group:'bird', writeup:"Burrows along coastal Patagonia in Chile and Argentina — the penguin who uses ground-shelter rather than huddling on ice. Annual migration of thousands of kilometers. Carries themes of: latitudinal commitment combined with seasonal extremity, the figure who occupies the temperate-climate version of an arctic vocation. Adapter-of-the-niche." },

    // MAMMALS (16)
    { slug:'mole', name:'Mole', group:'mammal', writeup:"The canonical mammalian burrower — velvety reversible-direction fur, reduced eyes, paddle-shaped front paws, exquisite tactile and vibration sensitivity. Spends entire life underground in tunnel networks; molehills are byproduct of excavation. Carries themes of: total commitment to subterranean vocation, the figure whose senses have specialized for the medium, work that produces visible-aboveground signs without ever showing the worker. The signature artist whose signature is everywhere and whose face is nowhere." },
    { slug:'pocket-gopher', name:'Pocket gopher', group:'mammal', writeup:"Solitary tunneling rodents with fur-lined cheek pouches for transporting food and bedding. Aggressively territorial — will fight to the death over burrow systems. Each gopher maintains an extensive personal tunnel network. Carries themes of: solitary specialist intelligence, the figure who has a domain and fiercely guards it, the introvert whose work is intricate and entirely their own. Storage as architecture, architecture as storage." },
    { slug:'groundhog', name:'Groundhog (woodchuck)', group:'mammal', writeup:"Large ground-squirrels that dig elaborate burrows with multiple chambers and entrances. Hibernate for months, lose 30%+ body weight. Burrows often inherited and expanded across generations. Carries themes of: prepared retreat into long sleep, the figure whose bigness is also their gentleness, seasonal rhythm at the body-scale. The figure whose schedule is set by the planet's tilt rather than any human calendar." },
    { slug:'rabbit', name:'European rabbit', group:'mammal', writeup:"Warren-builder par excellence — interconnected colonial burrow systems with multiple chambers, escape routes, social hierarchy. The warren is a household, not a single burrow. Carries themes of: communal infrastructure, the figure whose home is shared and structured, fast-reproductive abundance held in stable architecture. The rabbit's softness disguises the engineering rigor of the warren." },
    { slug:'prairie-dog', name:'Prairie dog', group:'mammal', writeup:"Primary excavator forming colonial 'towns' that historically covered hundreds of square miles. Sophisticated alarm-call vocabulary distinguishes specific predator types and even predator features. Carries themes of: civic-scale collective intelligence, articulate communication with referential precision, the figure whose town-building was the prairie's keystone before being nearly eradicated. Eusocial commitment without insect-level loss of individuality." },
    { slug:'aardvark', name:'Aardvark', group:'mammal', writeup:"Primary excavator of the African savanna — digs enormous burrows that house entire ecosystems of secondary occupants long after the aardvark has moved on. Eats up to 50,000 termites a night. Carries themes of: massive infrastructure-creation as side-effect of feeding, the figure whose unique vocation produces durable benefits for unrelated species. The maker of the home one will not live in." },
    { slug:'wombat', name:'Wombat', group:'mammal', writeup:"Marsupial primary excavator. Wombat burrows are large, elaborate, drone-mappable, and a single wombat may maintain up to a dozen. Famously cube-shaped scat — the only animal that produces it. Carries themes of: solid burrowing power in unlikely body-form, idiosyncratic biology, the figure whose strangeness is their excellence. Phlegmatic excavator-engineer." },
    { slug:'polar-bear', name:'Polar bear', group:'mammal', writeup:"The largest burrowing animal — pregnant females dig maternity dens in snow or earth and nurse cubs through the arctic winter without eating. The figure whose burrow is for the most-vulnerable phase of others' lives, not their own daily life. Carries themes of: massive scale of maternal-protective architecture, the figure whose hardest work is invisible and ends with offspring strong enough to leave. Apex predator who burrows only to mother." },
    { slug:'meerkat', name:'Meerkat', group:'mammal', writeup:"Carnivora burrower — meerkats live in extensive sentinel-organized warrens with sentry-rotation, group-childcare, coordinated foraging. Carries themes of: collective vigilance, the figure who takes their turn watching, mutual-aid that is not sentimental but structural. Tight-knit defensive sociality — the figure whose individualism is suspended in service of group survival." },
    { slug:'badger', name:'Badger', group:'mammal', writeup:"Builds extensive multi-generational setts — some European badger setts have been continuously occupied for over a century, with chambers expanded by successive generations. Famously fierce when cornered. Carries themes of: inherited architecture, the figure who lives in their ancestors' rooms, fierceness in defense of long-established territory. The home as legacy." },
    { slug:'kangaroo-rat', name:'Kangaroo rat', group:'mammal', writeup:"Small desert rodents whose 'granary' burrows can store up to 32 gallons of seeds — enormous food-stockpiles relative to body size. Don't drink water; metabolize it from seeds. Carries themes of: extreme preparation for scarcity, the figure whose tiny body manages outsized stores, capacity to survive on what others cannot. Resource-management as survival vocation." },
    { slug:'armadillo', name:'Armadillo', group:'mammal', writeup:"Nine-banded armadillos dig burrows in moist soil near creeks, can hold their breath up to six minutes to swim under or walk along stream-bottoms. Carries themes of: armored vulnerability, the figure whose protection is built-in but whose habitat-needs are specific and easily disrupted. Slow-reproducing, picky-territoried specialist." },
    { slug:'warthog', name:'Warthog', group:'mammal', writeup:"Warthogs use burrows (often abandoned aardvark dens) as nurseries — mothers back into the burrow tail-first so their tusks face any predator that approaches. Carries themes of: defensive parenting, the figure whose ferocity is reserved for the moment the offspring are at stake, opportunistic but effective shelter-use. The mother who positions herself as the door." },
    { slug:'naked-mole-rat', name:'Naked mole rat', group:'mammal', writeup:"Eusocial mammal — colonies of up to 80 individuals with a single breeding queen, soldiers, workers. Live in 3-kilometer tunnel systems entirely underground. Negligibly senescent (resistance to cancer and aging). Carries themes of: insect-like collective organization in mammalian body, exceptional longevity, the figure whose strangeness includes biological mysteries science is still working out. Outlier in every sense." },
    { slug:'pangolin', name:'Pangolin', group:'mammal', writeup:"Scaly mammal with chambered burrows large enough for a human to sleep in. Most-trafficked mammal in the world (for scales used in traditional medicine, despite no proven efficacy) — critically endangered. Eats ants and termites with a tongue longer than its body. Carries themes of: armored gentleness, the figure whose protection failed against species-level human predation, hidden architectural sophistication, the imperiled specialist." },
    { slug:'platypus', name:'Platypus', group:'mammal', writeup:"Monotreme — egg-laying mammal, venomous, electroreceptive bill, web-footed. Maintains nesting burrows along stream-banks AND multiple 'camping' burrows scattered through their territory, switching between them as needed. Carries themes of: irreducible weirdness, the figure who fits no clean category, distributed-home intelligence, the figure who has options. Multi-residency as survival strategy." },

    // === EXPANSION: 18 animals with hole-relationships beyond strict burrowing ===

    // ARTHROPODS - additional insects (corpse-cavity, hibernation-cavity)
    { slug:'ladybug', name:'Ladybug', group:'invertebrate', writeup:"Ladybugs cluster by the thousands in rock crevices, leaf-litter cavities, and wall-cracks to hibernate through winter. Aggregation pheromones draw new members to known cavities year after year. Carries themes of: collective huddle, inherited shelter, the figure whose survival depends on assembling with others, the small-charm-with-the-bright-armor that hides through the dark season. Shadow side: dependency on the cavity, the figure who cannot face winter alone." },
    { slug:'fly', name:'Fly', group:'invertebrate', writeup:"Flies lay eggs in the dark cavities of decomposing matter — wounds, carcasses, fermenting fruit, hollow stems. The maggots eat through their birth-cavity into adulthood. Carries themes of: turning what is dead into substrate for new life, comfort in environments others avoid, the figure who works at the boundary between living and rotting. Shadow side: the figure whose presence signals decay others cannot ignore." },
    { slug:'cockroach', name:'Cockroach', group:'invertebrate', writeup:"Cockroaches occupy wall-cavities, drain-pipes, foundation-cracks — the geometry of human architecture's neglected hollows. Survive nuclear radiation levels that destroy most life. Predate the dinosaurs. Carries themes of: ancient adaptive intelligence, comfort in human-rejected spaces, the figure whose persistence is so total it becomes contempt-target. Shadow side: nobody's friend, the figure who survives precisely BY being unwelcome." },

    // ARTHROPODS - additional crustaceans (reef-cavity dwellers)
    { slug:'lobster', name:'Lobster', group:'invertebrate', writeup:"Lobsters defend rocky-crevice homes for years, sometimes decades. Aggressive territorial behavior at the crevice mouth — claws displayed outward to discourage approach. Long-lived (some American lobsters reach 100+ years). Carries themes of: deep-water territorial defense, longevity earned through holding ground, the figure whose threshold-defense is also their persona. Shadow side: the figure whose entire identity is what they refuse to leave." },
    { slug:'octopus', name:'Octopus', group:'invertebrate', writeup:"Octopuses lair in reef holes, glass bottles, coconut shells — any cavity that fits the body. Decorate the entrance with shells. Famously intelligent. Each lair is a personal space-cosmos developed over weeks. Carries themes of: intelligence operating in solitary domestic space, decorative attention to the threshold, the figure whose interior life is rich precisely because they live alone. Shadow side: the figure whose lair becomes a fortress against contact." },

    // CHORDATES - reptiles (additional)
    { slug:'crocodile', name:'Crocodile', group:'reptile', writeup:"Female crocodiles dig nesting burrows on riverbanks, often retiring to underground dens during droughts that last for months. Some species (American alligators) excavate massive 'gator holes' that become wetland reservoirs other species depend on. Carries themes of: ancient maternal architecture, drought-survival through retreat, the apex-predator whose presence creates ecosystems for others. Shadow side: the figure whose territorial size becomes too large for others to share." },

    // CHORDATES - fish (cavity-dwellers)
    { slug:'reef-fish', name:'Reef fish', group:'fish', writeup:"Many reef fish (gobies, blennies, damselfish) live their entire adult lives in single coral-cavities, defending the same hole for years. Symbiotic relationships with shrimps that maintain the cavity in exchange for fish-protection. Carries themes of: micro-territorial life, reciprocal home-keeping, the figure whose entire universe fits inside a coral hole and is no smaller for it. Shadow side: the figure whose horizon shrinks to the cavity-mouth." },
    { slug:'shark', name:'Shark', group:'fish', writeup:"Nurse sharks and several reef-shark species use cave-systems and overhangs as resting spots, sometimes returning to the same cave nightly across years. The cave is the recovery-space; hunting happens elsewhere. Carries themes of: predatory power that requires retreat-space, the apex who needs darkness to recover, the figure whose hunting and resting are spatially separated. Shadow side: the figure whose recovery becomes inaccessibility to those who want them." },

    // CHORDATES - birds (tree-cavity nesters, cliff-cavity)
    { slug:'wood-duck', name:'Wood duck', group:'bird', writeup:"Wood ducks nest in tree-cavities up to 20 meters above ground, often abandoned woodpecker holes. Day-old chicks jump from the cavity to the ground or water below — total commitment to a new beginning before they have learned to fly. Carries themes of: trust in inherited architecture, the leap-of-faith built into the species, the figure who launches into life before capacity catches up to courage. Shadow side: the figure whose first leap defined them and they cannot stop leaping." },
    { slug:'eagle', name:'Eagle', group:'bird', writeup:"Eagles nest in cliff-face cavities and tree-fork hollows, building enormous nests added to year after year. Some bald eagle nests reach 4000kg in mass over generations. Carries themes of: monumental cumulative architecture, height as both home and hunting-vantage, the figure whose home grows heavier with each season they survive. Shadow side: the figure whose accumulated weight eventually breaks the support-structure." },

    // CHORDATES - mammals (additional)
    { slug:'fox', name:'Fox', group:'mammal', writeup:"Foxes both dig their own dens and squat in abandoned badger setts, marmot burrows, and prairie-dog towns. Versatility-of-housing is a survival trait. Carries themes of: opportunistic intelligence, willingness to inherit infrastructure when self-construction is unavailable, the figure who reads which option fits the moment. Shadow side: the figure whose flexibility prevents the deep-investment in one home." },
    { slug:'wolf', name:'Wolf', group:'mammal', writeup:"Wolves dig dens for raising pups — used only during the early-rearing season, abandoned afterward. The den is a maternal-phase architecture, not a year-round home. Carries themes of: temporary structure built for the most vulnerable phase, the pack-animal whose den-need is generational rather than permanent, the figure whose home-building is in service of others' growth. Shadow side: the figure who builds for others and never for themselves." },
    { slug:'bear', name:'Bear', group:'mammal', writeup:"Black and brown bears hibernate in caves, hollow logs, and excavated dens for 4-7 months. Heart-rate drops to 8 beats per minute. Wake to no food cached, no fat reserves expected to last beyond emergence. Carries themes of: deep retreat as annual practice, faith in the conditions of return, the figure whose long sleep is also their longest discipline. Shadow side: the figure whose hibernation extends past the right season for waking." },
    { slug:'mouse', name:'Mouse', group:'mammal', writeup:"Mice dig elaborate burrow-systems in fields, walls, and stored-grain spaces. Deer mice maintain seed-caches in chambers separate from sleeping-chambers. Famously fast-reproducing. Carries themes of: small-scale architectural cleverness, abundance achieved through volume, the figure whose smallness is offset by quantity. Shadow side: the figure who multiplies past the carrying-capacity of any single home." },
    { slug:'rat', name:'Rat', group:'mammal', writeup:"Rats build complex burrow-systems with multiple entrances, escape routes, food-storage chambers. Adapt to virtually any environment human-made or natural. Carries themes of: adaptive intelligence at the urban scale, the figure who reads infrastructure and exploits it, social-cooperation in dense colonies. Shadow side: cultural-association with disease and contempt, the figure whose competence is read as threat." },
    { slug:'hamster', name:'Hamster', group:'mammal', writeup:"Wild hamsters dig burrows up to two meters deep with separate chambers for sleeping, food-hoarding, and waste. Cheek-pouches transport seeds back to the burrow. Solitary territorial defenders. Carries themes of: meticulous home-organization, hoarding as central practice, the small figure with the well-managed interior. Shadow side: the figure whose hoard becomes the entire identity." },
    { slug:'hedgehog', name:'Hedgehog', group:'mammal', writeup:"Hedgehogs nest in hedgerow cavities, tree-roots, leaf-litter mounds. Hibernate in scrap-cavities they accumulate from autumn. Roll into spiny-balls when threatened — armor IS the response. Carries themes of: gentle solitary life with built-in defensive posture, the figure whose vulnerability is the engine of their armor, hedgerow-comfort. Shadow side: the figure who curls up and waits when action would serve better." },
    { slug:'otter', name:'Otter', group:'mammal', writeup:"River otters dig dens (called 'holts') into riverbanks with underwater entrances. Sea otters hold paws while sleeping in kelp forests. Famously playful. Carries themes of: the architectural-sociability paradox — solitary den-builders who play in groups, the figure whose home is a bank-cavity and whose social life is the open water. Shadow side: the figure who treats serious moments as play and play moments as performance." },
    { slug:'beaver', name:'Beaver', group:'mammal', writeup:"Beavers build BOTH lodges (above-water domed structures) AND bank-burrows. The lodge is a constructed home, the bank-burrow is an excavated alternative. Famously change ecosystems through dam-engineering. Carries themes of: monumental landscape-shaping, the figure whose home-building reshapes everything downstream, dual-housing strategy. Shadow side: the figure whose engineering changes ecosystems faster than ecosystems can adapt." },
    { slug:'squirrel', name:'Squirrel', group:'mammal', writeup:"Squirrels nest in tree-cavities (dreys made in hollow trunks) AND maintain hundreds of cache-holes in the ground for nut-storage, recovering them by spatial memory. Carries themes of: dual-vertical-life, abundant-distributed-storage, the figure whose home is in the canopy and whose pantry is the soil. Shadow side: the figure whose distributed strategy means no single hole is fully secure." },

    // === EXPANSION 2: Terrestrial gaps ===

    // ARTHROPODS - additional insects
    { slug:'ant', name:'Ant', group:'invertebrate', writeup:"Ants build underground colonies with specialized chambers — brood, food-storage, queen, fungal gardens. Workers maintain ventilation. Colonies last for years. Carries themes of: distributed-cognition at colony scale, role-specialization, the figure whose individual contribution disappears into emergent collective intelligence. Shadow side: the figure who cannot exist outside the colony and does not know who they are alone." },
    { slug:'cicada-killer', name:'Cicada killer wasp', group:'invertebrate', writeup:"Solitary wasps that dig burrows in sandy soil and provision them with paralyzed cicadas as living-food for their larvae. Single-mother architecture. Carries themes of: maternal preparation for offspring you will never meet, surgical hunting in service of a future-generation, solo specialist craft. Shadow side: the figure whose entire life is preparation for someone else's life." },

    // CHORDATES - additional reptiles
    { slug:'desert-tortoise', name:'Desert tortoise', group:'reptile', writeup:"Desert tortoises spend up to 95% of their lives in burrows, escaping extreme desert temperatures and conserving body moisture. Multiple burrows per territory. Carries themes of: extreme retreat as survival, the figure whose visible-time is a fraction of their actual time, hidden long-life. Shadow side: the figure whose burrow-dependence makes them fragile to habitat-disruption." },
    { slug:'hognose-snake', name:'Hognose snake', group:'reptile', writeup:"Hognose snakes burrow into loose soil with their upturned snouts, creating shelter and hunting toad-prey underground. Famous for theatrical death-feigning when threatened. Carries themes of: subterranean ambush combined with dramatic threat-response, the figure who plays-dead rather than fight. Shadow side: the figure whose performance becomes their default — pretending becomes harder to stop than to start." },
    { slug:'sidewinder', name:'Sidewinder rattlesnake', group:'reptile', writeup:"Sidewinders bury themselves shallowly in desert sand for ambush, leaving only the head exposed. Move sideways across sand to minimize contact with hot surface. Carries themes of: minimal-contact navigation, ambush from sand-cover, the figure whose strategy is to be barely there. Shadow side: the figure whose minimal contact with surfaces becomes inability to engage at full." },
    { slug:'komodo-dragon', name:'Komodo dragon', group:'reptile', writeup:"Komodo dragons dig nesting burrows up to 9 meters deep AND occupy abandoned megapode mounds for nest-site. Females use multiple decoy nests to confuse predators of eggs. Carries themes of: massive predator with maternal craft, the figure whose ferocity contains careful preparation. Shadow side: the figure whose intimidation hides the patient long-game beneath." },

    // CHORDATES - additional birds
    { slug:'kingfisher', name:'Kingfisher', group:'bird', writeup:"Kingfishers excavate horizontal nesting tunnels into riverbanks, sometimes a meter deep, lined with regurgitated fish-bones. Carries themes of: precision-fishing combined with riverbank-sculpture, the figure who hunts in water and nests in earth — moving between elements. Shadow side: the figure whose home depends on a specific habitat boundary that human intervention often destroys." },
    { slug:'sand-martin', name:'Sand martin', group:'bird', writeup:"Sand martins excavate colonial nest-tunnels in sandy riverbanks, with hundreds of pairs nesting side-by-side. Carries themes of: colonial-architectural intelligence, the figure whose home is one cell in an apartment-block of similar lives, neighborly proximity as protection. Shadow side: the figure whose individual identity dissolves into the colony-pattern." },
    { slug:'bee-eater', name:'Bee-eater', group:'bird', writeup:"Bee-eaters dig long sandy-bank tunnels (up to 2.5m) for nesting. Carries themes of: long-tunnel craft, the figure whose nest is hidden deep within the bank, brilliantly-colored bird that lives in earthen darkness when not hunting. Shadow side: the figure whose visible-color belies the hidden interior life." },
    { slug:'shearwater', name:'Shearwater', group:'bird', writeup:"Shearwaters nest in coastal burrows, returning to the same hole across many years. Some species fly thousands of kilometers between breeding-burrow and feeding-grounds. Carries themes of: long-distance migration anchored to a single burrow, the figure whose vast-range movement returns always to one specific home. Shadow side: the figure whose home-fidelity in a changing world becomes a tether they cannot cut." },

    // CHORDATES - additional mammals
    { slug:'marmot', name:'Alpine marmot', group:'mammal', writeup:"Marmots dig elaborate alpine burrow-systems with multiple chambers, hibernate 6-9 months annually. Family groups share warming-burrows in winter. Carries themes of: high-altitude domestic intelligence, hibernation as primary mode, the figure whose communal warmth is the survival strategy. Shadow side: the figure whose long sleep means short opportunity-windows for action." },
    { slug:'ground-squirrel', name:'Ground squirrel', group:'mammal', writeup:"Ground squirrels maintain extensive tunnel networks with multiple chambers. Hibernate in deep chambers. Sentinel-system warns colony of predators. Carries themes of: colonial vigilance, the figure who alternates between sentinel-duty and community-life, the chambered home. Shadow side: the figure whose vigilance becomes paranoia, who cannot stop scanning even when safe." },
    { slug:'chipmunk', name:'Chipmunk', group:'mammal', writeup:"Chipmunks dig burrows up to 3m long with separate chambers for nesting, food-storage, and waste — with the entrance plugged when sleeping. Cheek-pouches carry seeds. Carries themes of: meticulous home-organization, the figure who sorts spaces by function, hoarder-architecture. Shadow side: the figure whose orderliness becomes inflexibility." },
    { slug:'lemming', name:'Lemming', group:'mammal', writeup:"Lemmings construct under-snow tunnel-systems through the arctic winter, breeding throughout the dark months. Population cycles drive mass-emigrations every few years. Carries themes of: subnivean (under-snow) intelligence, persistence through darkness, the figure whose population dynamics shape arctic ecosystems. Shadow side: the figure whose mass-movement is read as madness rather than as response to overcrowding." },
    { slug:'jerboa', name:'Jerboa', group:'mammal', writeup:"Jerboas dig elaborate desert burrows that maintain stable humidity at depth, plugging entrances against heat. Bipedal hopping on long hind legs. Carries themes of: water-economy through retreat, the figure whose body is so adapted to one environment they cannot live elsewhere. Shadow side: the figure whose specialized adaptation becomes vulnerability." },
    { slug:'vole', name:'Vole', group:'mammal', writeup:"Voles maintain runway-systems through grass, with shallow burrows for nesting and food-storage. Famous prey-species — most ecosystems depend on vole-populations. Carries themes of: foundational position in food-webs, the figure whose abundance feeds the larger system, the small life that everything else depends on. Shadow side: the figure who exists primarily as nutrition for others." },
    { slug:'fennec-fox', name:'Fennec fox', group:'mammal', writeup:"Fennec foxes dig sandy desert dens with multiple entrances, escaping daytime heat in cool burrows. Largest ears of any canid help dissipate heat AND locate underground prey. Carries themes of: sensory-attunement combined with retreat-architecture, the figure whose physical features serve double-purpose. Shadow side: the smallest fox in the world — the figure whose adaptive cleverness still cannot offset their physical vulnerability." },
    { slug:'arctic-fox', name:'Arctic fox', group:'mammal', writeup:"Arctic foxes use complex multi-entrance dens for raising pups — some dens have been used by successive fox-generations for 300+ years. Carries themes of: inherited-architecture across generations, the figure whose home contains ancestral memory, ancient continuity in a fierce climate. Shadow side: the figure whose dependence on a single den-system fails when permafrost shifts." },
    { slug:'coyote', name:'Coyote', group:'mammal', writeup:"Coyotes dig dens during pup-rearing season, often modifying badger or fox burrows. Pair-bonded; both parents tend the den. Carries themes of: opportunistic-architecture, the figure who improves what others built, partnership in the den-keeping. Shadow side: the figure whose adaptability is read as menace." },
    { slug:'african-wild-dog', name:'African wild dog', group:'mammal', writeup:"African wild dogs den communally, often using abandoned aardvark or warthog burrows. Pack of 6-20 raises pups collectively — every adult helps. Carries themes of: communal-rearing, the figure whose offspring are everyone's offspring, the alpha-pair extends parenthood across the pack. Shadow side: the figure whose dependence on intact pack-structure means losing one means losing all." },
    { slug:'skunk', name:'Skunk', group:'mammal', writeup:"Skunks use multi-entrance winter dens, often communal. Famous chemical-defense — the figure whose threat-display does not require physical strength. Carries themes of: chemical-warning rather than violence, the figure whose presence announces itself before contact. Shadow side: the figure whose first-line-of-defense is so effective they have not developed others." },
    { slug:'muskrat', name:'Muskrat', group:'mammal', writeup:"Muskrats dig bank-burrows along waterways with underwater entrances, OR build above-water lodge-mounds where banks are absent. Both architectures depend on water-cover. Carries themes of: dual-architecture-strategy, water as the primary medium, the figure whose home is always partly submerged. Shadow side: the figure whose habitat depends on hydrological balance human management often disrupts." },
    { slug:'springhare', name:'Springhare', group:'mammal', writeup:"Springhares dig deep desert burrows used for daytime sleep, emerging only at night. Bipedal hopping like a tiny kangaroo. Carries themes of: nocturnal life, the figure whose visible-time is darkness only, hopping-locomotion combined with deep-retreat. Shadow side: the figure whose nocturnality means missing what happens by day." },
    { slug:'numbat', name:'Numbat', group:'mammal', writeup:"Numbats shelter in hollow logs and short burrows during the night, foraging diurnally — opposite to most marsupials. Termite-specialists. Carries themes of: diurnal-marsupial-anomaly, the figure who lives against the schedule of their kin, log-cavity as primary home. Shadow side: critically-endangered, the figure whose niche-specialization makes recovery slow." },
    { slug:'bilby', name:'Bilby', group:'mammal', writeup:"Bilbies dig spiral-shaped burrows up to 3m deep, with multiple individuals each maintaining several burrows. Famous as Australia's 'Easter bilby' (alternative to imported rabbit-imagery). Carries themes of: spiral-architectural signature, the figure whose home-shape itself is recognizable, multi-residence resilience. Shadow side: the figure whose existence has been threatened by introduced species occupying their burrows." },
    { slug:'echidna', name:'Echidna', group:'mammal', writeup:"Echidnas dig temporary shallow burrows quickly for shelter when threatened — straight down into soil, only spines visible. Egg-laying mammal (monotreme). Carries themes of: rapid-defensive-burrowing, the figure who can vanish into the ground in seconds, ancient-monotreme-lineage. Shadow side: the figure whose defensive strategy works against most threats but cannot help against habitat-loss." },
    { slug:'tenrec', name:'Tenrec', group:'mammal', writeup:"Tenrecs (Madagascar) dig small burrows or use tree-hollows — convergent evolution toward shrew/hedgehog/mole forms despite no relation. Some species hibernate 9 months. Carries themes of: convergent-form-with-different-ancestry, the figure who looks-like other animals but came from elsewhere, island-evolution. Shadow side: the figure whose Madagascar-isolation makes them critically vulnerable to habitat change." },

    // === MARINE ===

    // MOLLUSCS - additional cephalopods (octopus already added)
    // Wait - octopus is already in the list. Adding the moray eel and others below.

    // CHORDATES - marine fish
    { slug:'moray-eel', name:'Moray eel', group:'marine-fish', writeup:"Moray eels live in reef-crevices and rock-holes, returning to the same den for years. Mouth open displays not as threat but to push water across gills. Carries themes of: faithful-territory, the figure whose menacing-appearance is misread breathing-mechanics, fixed-residence in chaotic-habitat. Shadow side: the figure whose unchanging-position makes them visible to those who would harm them." },
    { slug:'garden-eel', name:'Garden eel', group:'marine-fish', writeup:"Garden eels build vertical burrows in seabed sand, half-emerging to feed on plankton, retreating instantly when threatened. Colonies of hundreds look like an underwater meadow. Carries themes of: half-emergence-as-permanent-state, the figure who lives at the boundary between burrow and current, neighborly-isolation. Shadow side: the figure whose retreat is so reflexive they cannot fully commit to emergence." },
    { slug:'jawfish', name:'Jawfish', group:'marine-fish', writeup:"Jawfish dig vertical sand-burrows reinforced with carefully-placed shells and pebbles. Males mouth-brood eggs while staying inside the burrow. Carries themes of: architectural-care combined with paternal-care, the figure whose home is also the nursery, choosing each pebble that lines the entrance. Shadow side: the figure whose burrow-investment makes relocation traumatic." },
    { slug:'goby', name:'Shrimp goby', group:'marine-fish', writeup:"Shrimp gobies share burrows with pistol shrimps — the shrimp digs, the goby watches for predators. Lifelong symbiotic partnership. Carries themes of: cross-species partnership, the figure whose role is defined by what the partner does, mutualism-as-architecture. Shadow side: the figure whose function depends on someone else continuing to dig." },
    { slug:'flounder', name:'Flounder', group:'marine-fish', writeup:"Flounders bury themselves in sand with only eyes exposed, blending with substrate. Body asymmetry — both eyes migrate to one side as the fish matures. Carries themes of: full-camouflage-burial, the figure whose body itself reorganizes for the burrow-life, hidden-emergence. Shadow side: the figure whose adaptation to one orientation means they cannot return to the original form." },
    { slug:'stingray', name:'Stingray', group:'marine-fish', writeup:"Stingrays bury themselves in sand for ambush and rest, leaving only eyes and barb-tail visible. Pectoral-fin undulation creates the burial-cloud. Carries themes of: graceful-disappearance-into-substrate, the figure whose flight-and-flatness combine, defensive-burial. Shadow side: the figure whose camouflage means accidentally-stepped-on by waders, defensive-strike when surprised." },
    { slug:'parrotfish', name:'Parrotfish', group:'marine-fish', writeup:"Parrotfish carve cavities in coral with their beaked teeth as they feed, AND shelter in reef-cavities at night. Each parrotfish produces hundreds of pounds of sand annually as coral-byproduct. Carries themes of: feeding-as-architecture, the figure whose eating reshapes the seascape, beach-builder. Shadow side: the figure whose continuous-activity destroys what they live in." },
    { slug:'clownfish', name:'Clownfish', group:'marine-fish', writeup:"Clownfish live within the protective cavity formed by sea anemone-tentacles, immune to the stinging cells. Lifelong residence. Carries themes of: chosen-symbiotic-cavity, the figure whose home is another organism, immune-only-to-your-chosen-poison. Shadow side: the figure whose entire life depends on a single host that may or may not survive climate-stress." },
    { slug:'blenny', name:'Blenny', group:'marine-fish', writeup:"Blennies live in small reef-holes, often other species' abandoned shells or worm-tubes. Permanent residence. Carries themes of: opportunistic-occupancy, the figure who finds a hole and stays, small-bodied tenacity. Shadow side: the figure whose hole-dependence means they cannot range." },

    // ARTHROPODS - marine
    { slug:'pistol-shrimp', name:'Pistol shrimp', group:'marine-invertebrate', writeup:"Pistol shrimp dig burrows AND maintain them in symbiosis with watchful gobies. Famous for cavitation-bubble-strike that stuns prey with sound louder than a gunshot. Carries themes of: architectural-craft combined with weaponized-precision, the figure whose tool is sound itself, partnered-defense. Shadow side: the figure whose violent-precision is locked in service of someone else's vigilance." },
    { slug:'peacock-mantis-shrimp', name:'Peacock mantis shrimp', group:'marine-invertebrate', writeup:"Mantis shrimp dig U-shaped burrows in sediment, returning to them after hunting. Most complex visual system in the animal kingdom — 16 photoreceptor types. Carries themes of: home-base-pattern, the figure whose perceptual-range exceeds everyone around them, hidden-extreme-cognition. Shadow side: the figure whose perceptual-richness is invisible to those who could appreciate it." },
    { slug:'ghost-shrimp', name:'Ghost shrimp', group:'marine-invertebrate', writeup:"Ghost shrimp dig complex burrow-networks in marine sediments — multiple chambers, interconnected tunnels. Their digging aerates and reshapes seabeds. Carries themes of: invisible-engineering, the figure whose presence transforms the substrate without recognition, ecosystem-engineer-without-credit. Shadow side: the figure whose work is disregarded precisely because it is foundational." },
    { slug:'mole-crab', name:'Mole crab', group:'marine-invertebrate', writeup:"Mole crabs bury themselves in the swash zone — the wave-line of beach — emerging only their antennae to filter food. Move position with every tide. Carries themes of: continuous-relocation-with-the-tide, the figure who moves precisely with the rhythm-of-water, filter-feeding-from-burial. Shadow side: the figure whose entire life is at the boundary of zones — always between." },
    { slug:'horseshoe-crab', name:'Horseshoe crab', group:'marine-invertebrate', writeup:"Horseshoe crabs bury themselves in beach-sand for protection AND for spawning, females laying eggs deep in tidal-zones. Living-fossil — predates dinosaurs by 200 million years. Carries themes of: ancient-continuity, the figure whose body-plan has not needed updating in 450 million years, ritual-spawning. Shadow side: the figure whose ancient-strategy now confronts threats their evolution did not prepare for." },
    { slug:'hermit-crab', name:'Hermit crab', group:'marine-invertebrate', writeup:"Hermit crabs occupy abandoned snail-shells, upgrading to larger ones as they grow. Form lines to swap shells when one is vacated. Carries themes of: borrowed-architecture, the figure whose home is permanently-someone-else's, growth-requires-relocation. Shadow side: the figure whose dependence on found-housing means they are always one shell-shortage away from crisis." },

    // ANNELIDS - marine worms
    { slug:'lugworm', name:'Lugworm', group:'marine-invertebrate', writeup:"Lugworms construct U-shaped burrows in tidal sand, processing sediment through their gut. Visible only by the cast-pile at one end and depression at the other. Carries themes of: U-shaped-architecture, the figure whose work is visible only by its byproducts, sediment-as-substrate-for-life. Shadow side: the figure whose feeding-mode requires precisely the conditions human pollution most disrupts." },
    { slug:'bobbit-worm', name:'Bobbit worm', group:'marine-invertebrate', writeup:"Bobbit worms construct deep burrows in seafloor sediment, leaving only mandibles visible to ambush passing fish. Bodies up to 3 meters long. Carries themes of: extreme-burrow-depth combined with ambush-emergence, the figure whose visible-fraction conceals a much-larger-hidden-self. Shadow side: the figure whose ambush-strategy requires permanent partial-concealment." },
    { slug:'tube-worm', name:'Tube worm', group:'marine-invertebrate', writeup:"Tube worms inhabit calcium-tubes anchored to seafloor — at hydrothermal vents, some species live 2+ meters tall in chemosynthetic darkness. Have no mouth, no gut — fed by symbiotic bacteria. Carries themes of: alien-mode-of-being, the figure whose entire metabolism depends on partnerships, deep-darkness-life. Shadow side: the figure whose existence is so specialized they cannot survive any change to vent-conditions." }

  ];

  global.BurrowingAnimals = ANIMALS;

})(typeof window !== 'undefined' ? window : this);
