#!/usr/bin/env python3
"""Idempotently import Polymythcal Set 5 — Media Literacy.

Covers youth and professional film, documentary, photography, journalism,
communication studies, games, advertising, immersive media, podcasts, and
media-and-information literacy. Confirmed stages remain separate from annual
watches and source inconsistencies remain explicit.
"""
from pathlib import Path
from polymythcal_set_import_common import make_record as R, make_watch as W, apply_import

ROOT = Path(__file__).resolve().parents[1]
CONFIG = {
    "src": "manual-polymythcal-media-literacy-set5-2026-08-13",
    "research_set": "5-Media-Literacy",
    "checked": "2026-08-13T20:08:00-04:00",
    "domain_label": "Media Literacy",
    "topic_slug": "media-literacy",
    "set_tag": "Set 5",
    "entry_family": "media-literacy",
    "field_name": "media_literacy_subfields",
    "metadata_key": "polymythcal_media_literacy_set5_update_2026_08_13",
    "sources_metadata_key": "polymythcal_media_literacy_set5_2026_08_13",
    "research_filename": "polymythcal-research-set-5-media-literacy-2026-08-13.json",
    "research_dirname": "polymythcal-set5-media-literacy-2026-08-13",
    "ledger_schema": "polymythcal-media-literacy-set5-research-ledger-v1",
    "cl_ids": [f"CL-WEB-{n}" for n in range(212, 220)],
    "ledger_notes": [
        "Film, photography, journalism, games, advertising, podcasting, communication studies, and media-information literacy are indexed independently.",
        "Submission openings, deadlines, finalist announcements, festivals, and award ceremonies remain linked but distinct.",
        "Exact grades and ages are indexed only when stated by the organizer.",
        "Annual-watch markers and contradictory official text remain explicit rather than being converted into invented dates.",
    ],
}

records = []
def A(event): records.append(event)

# Photography — Sony World Photography Awards 2027.
sony = "https://www.worldphoto.org/sony-world-photography-awards"
A(R(config=CONFIG, id="sony-world-photography-student-2027-deadline", title="Sony World Photography Awards 2027 — Student competition deadline", date="2026-11-27T16:00:00+00:00", source_url="https://www.worldphoto.org/sony-world-photography-awards/student", organizer="World Photography Organisation", summary="Deadline for the 2027 Student competition, open through participating higher-education photography programs.", subfields=["Photography","Student Media"], opportunity_kind="photography competition", age_band="Higher-education photography students", education_levels=["college","undergraduate"], participation_unit="individual student through institution", access_route="participating institution", prize_form="international recognition and program prizes", submission_url="https://www.worldphoto.org/sony-world-photography-awards/student", calendar_stage="submission closing", timezone="UTC"))
A(R(config=CONFIG, id="sony-world-photography-youth-2027-deadline", title="Sony World Photography Awards 2027 — Youth competition deadline", date="2027-01-05T16:00:00+00:00", source_url="https://www.worldphoto.org/sony-world-photography-awards/youth", organizer="World Photography Organisation", summary="Deadline for the free Youth competition for photographers aged 19 and under.", subfields=["Photography","Youth Media"], opportunity_kind="photography competition", age_band="Age 19 and under", participation_unit="individual photographer", access_route="direct submission", prize_form="international recognition and photography prizes", submission_url="https://www.worldphoto.org/sony-world-photography-awards/youth", calendar_stage="submission closing", timezone="UTC"))
A(R(config=CONFIG, id="sony-world-photography-open-2027-deadline", title="Sony World Photography Awards 2027 — Open competition deadline", date="2027-01-05T16:00:00+00:00", source_url=sony, organizer="World Photography Organisation", summary="Deadline for the 2027 Open competition for single images.", subfields=["Photography","Open Media"], opportunity_kind="photography competition", age_band="Open photographers", education_levels=["open","professional"], participation_unit="individual photographer", access_route="direct submission", prize_form="international recognition and photography prizes", submission_url=sony, calendar_stage="submission closing", timezone="UTC"))
A(R(config=CONFIG, id="sony-world-photography-professional-2027-deadline", title="Sony World Photography Awards 2027 — Professional competition deadline", date="2027-01-12T16:00:00+00:00", source_url=sony, organizer="World Photography Organisation", summary="Deadline for the 2027 Professional competition for photographic series.", subfields=["Photography","Professional Media"], opportunity_kind="photography competition", age_band="Professional photographers", education_levels=["professional"], participation_unit="individual photographer", access_route="direct submission", prize_form="international recognition and photography prizes", submission_url=sony, calendar_stage="submission closing", timezone="UTC"))

# Film and documentary festivals / youth film.
hotdocs = "https://hotdocs.ca/industry/submit-a-film"
A(R(config=CONFIG, id="hot-docs-2027-submissions-open", title="Hot Docs 2027 — film submissions open", date="2026-09-23T00:00:00-04:00", source_url=hotdocs, organizer="Hot Docs", summary="Opening of film submissions for the 2027 Hot Docs Canadian International Documentary Festival.", subfields=["Documentary","Film Festivals"], opportunity_kind="documentary submission", age_band="Eligible documentary filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=hotdocs, series_title="Hot Docs 2027", series_role="child", calendar_stage="submissions opening", parent_id="hot-docs-2027-festival"))
A(R(config=CONFIG, id="hot-docs-2027-early-deadline", title="Hot Docs 2027 — early submission deadline", date="2026-10-29T00:00:00-04:00", source_url=hotdocs, organizer="Hot Docs", summary="Early submission deadline for the 2027 documentary festival.", subfields=["Documentary","Film Festivals"], opportunity_kind="documentary submission", age_band="Eligible documentary filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=hotdocs, series_title="Hot Docs 2027", series_role="child", calendar_stage="early deadline", parent_id="hot-docs-2027-festival"))
A(R(config=CONFIG, id="hot-docs-2027-regular-deadline", title="Hot Docs 2027 — regular submission deadline", date="2026-12-10T00:00:00-05:00", source_url=hotdocs, organizer="Hot Docs", summary="Regular submission deadline for the 2027 documentary festival.", subfields=["Documentary","Film Festivals"], opportunity_kind="documentary submission", age_band="Eligible documentary filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=hotdocs, series_title="Hot Docs 2027", series_role="child", calendar_stage="regular deadline", parent_id="hot-docs-2027-festival"))
A(R(config=CONFIG, id="hot-docs-2027-late-deadline", title="Hot Docs 2027 — late submission deadline", date="2027-01-04T00:00:00-05:00", source_url=hotdocs, organizer="Hot Docs", summary="Late submission deadline for the 2027 documentary festival.", subfields=["Documentary","Film Festivals"], opportunity_kind="documentary submission", age_band="Eligible documentary filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=hotdocs, series_title="Hot Docs 2027", series_role="child", calendar_stage="late deadline", parent_id="hot-docs-2027-festival"))
A(R(config=CONFIG, id="hot-docs-2027-festival", title="Hot Docs Canadian International Documentary Festival 2027", date="2027-04-23T00:00:00-04:00", end_date="2027-05-02T23:59:00-04:00", source_url=hotdocs, organizer="Hot Docs", summary="The 2027 Hot Docs festival in Toronto, linked to its separate submission stages.", subfields=["Documentary","Film Festivals"], record_kind="event", type="festival", age_band="Public audiences and documentary industry", education_levels=["open","professional"], city="Toronto", province="Ontario", country="Canada", venue="Toronto venues", series_title="Hot Docs 2027", series_role="parent", calendar_stage="festival run"))

connecther = "https://connectherfilmfest.org/submit/"
A(R(config=CONFIG, id="connecther-film-festival-2026-deadline", title="ConnectHER Film Festival 2026 submission deadline", date="2026-10-01T00:00:00-04:00", source_url=connecther, organizer="ConnectHER", summary="Deadline for short films by creators aged 13–25 addressing issues affecting women and girls. The current rules require human authorship and limit generative-AI use.", subfields=["Film","Social-Issue Media","Youth Media"], opportunity_kind="youth film competition", age_band="Ages 13-25", participation_unit="individual or eligible team", access_route="direct submission", prize_form="cash awards and recognition", submission_url=connecther, calendar_stage="submission closing", ai_rule="Human authorship required; generative AI is restricted under the current rules."))

oneearth = "https://www.oneearthfilmfest.org/contest-details"
A(R(config=CONFIG, id="one-earth-young-filmmakers-2027-deadline", title="One Earth Young Filmmakers Contest 2027 deadline", date="2027-06-25T23:59:00-05:00", source_url=oneearth, organizer="One Earth Film Festival", summary="Free international environmental-film deadline for entrants from Grade 3 through age 25.", subfields=["Film","Environmental Media","Youth Media"], opportunity_kind="environmental film contest", age_band="Grade 3 through age 25", exact_grades=[f"Grade {n}" for n in range(3,13)], education_levels=["elementary","secondary","undergraduate"], participation_unit="individual or eligible team", access_route="direct submission", prize_form="awards, screening, and recognition", submission_url=oneearth, calendar_stage="submission closing", timezone="America/Chicago"))
A(R(config=CONFIG, id="one-earth-young-filmmakers-2027-premieres", title="One Earth Young Filmmakers Contest 2027 premieres", date="2027-09-01T00:00:00-04:00", source_url=oneearth, organizer="One Earth Film Festival", summary="September 2027 premiere period for selected One Earth Young Filmmakers Contest work; exact screening dates remain organizer-defined.", subfields=["Film","Environmental Media","Youth Media"], record_kind="event", type="screening", age_band="Selected Grade 3–age 25 filmmakers and public audiences", education_levels=["elementary","secondary","undergraduate","open"], participation_unit="selected filmmaker", access_route="selection from contest", parent_id="one-earth-young-filmmakers-2027-deadline", series_title="One Earth Young Filmmakers Contest 2027", series_role="child", calendar_stage="premiere period", date_precision="month", time_precision="unknown", qualification_reasons=["exact-screening-date-unconfirmed","time-unconfirmed"]))

myhero = "https://myhero.com/festival-information"
A(R(config=CONFIG, id="my-hero-international-film-festival-2026-deadline", title="MY HERO International Film Festival 2026 deadline", date="2026-09-01T00:00:00-04:00", source_url=myhero, organizer="The MY HERO Project", summary="Final listed deadline for student and professional short films celebrating heroes. Student entry is free.", subfields=["Film","Youth Media","Social-Issue Media"], opportunity_kind="film competition", age_band="Students and professional filmmakers", education_levels=["elementary","secondary","undergraduate","professional"], participation_unit="individual or team", access_route="direct submission", prize_form="festival recognition and awards", submission_url=myhero, calendar_stage="submission closing", source_inconsistency="The official page contains stale 2022 wording alongside the current 2026 festival information."))
A(R(config=CONFIG, id="my-hero-immersive-storytelling-2026-deadline", title="MY HERO Immersive Storytelling Award 2026 deadline", date="2026-09-01T00:00:00-04:00", source_url="https://myhero.com/immersive-storytelling-award", organizer="The MY HERO Project", summary="Deadline for immersive and emerging-media storytelling about heroes and positive change.", subfields=["Immersive Media","Digital Storytelling","Youth Media"], opportunity_kind="immersive storytelling competition", age_band="Students and creators", education_levels=["secondary","undergraduate","professional"], participation_unit="individual or team", access_route="direct submission", prize_form="festival recognition and awards", submission_url="https://myhero.com/immersive-storytelling-award", calendar_stage="submission closing"))
A(W(config=CONFIG, id="my-hero-sylvia-earle-ocean-conservation-2027-watch", title="MY HERO Sylvia Earle Ocean Conservation Award 2027 watch", marker="2027-01-01T00:00:00-05:00", source_url="https://myhero.com/sylvia-earle-ocean-conservation-award", organizer="The MY HERO Project", summary="The organizer states that the award will reopen in January 2027, but no exact opening or deadline is yet published.", subfields=["Film","Environmental Media","Youth Media"], opportunity_kind="environmental film award", age_band="Student and professional filmmakers", education_levels=["secondary","undergraduate","professional"], recurrence_note="Expected to reopen in January 2027."))

regard = "https://festivalregard.com/en/call-for-entries"
A(R(config=CONFIG, id="regard-2027-early-deadline", title="REGARD Festival 2027 — early submission deadline", date="2026-09-15T00:00:00-04:00", source_url=regard, organizer="REGARD Festival", summary="Early submission deadline for the 2027 international short-film festival.", subfields=["Short Film","Film Festivals"], opportunity_kind="short-film submission", age_band="Eligible filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=regard, parent_id="regard-festival-2027", series_title="REGARD Festival 2027", series_role="child", calendar_stage="early deadline"))
A(R(config=CONFIG, id="regard-2027-regular-deadline", title="REGARD Festival 2027 — regular submission deadline", date="2026-10-15T00:00:00-04:00", source_url=regard, organizer="REGARD Festival", summary="Regular submission deadline for the 2027 international short-film festival.", subfields=["Short Film","Film Festivals"], opportunity_kind="short-film submission", age_band="Eligible filmmakers", education_levels=["professional"], participation_unit="filmmaker or rights holder", access_route="online submission", submission_url=regard, parent_id="regard-festival-2027", series_title="REGARD Festival 2027", series_role="child", calendar_stage="regular deadline"))
A(W(config=CONFIG, id="regard-2027-last-minute-deadline-watch", title="REGARD Festival 2027 — last-minute submission phase watch", marker="2026-11-01T00:00:00-04:00", source_url=regard, organizer="REGARD Festival", summary="The official call identifies a last-minute phase but does not yet provide a recoverable exact closing date.", subfields=["Short Film","Film Festivals"], opportunity_kind="short-film submission", parent_id="regard-festival-2027", series_title="REGARD Festival 2027", series_role="child", calendar_stage="last-minute phase", qualification_reasons=["date-unconfirmed","time-unconfirmed"]))
A(R(config=CONFIG, id="regard-festival-2027", title="REGARD International Short Film Festival 2027", date="2027-03-17T00:00:00-04:00", end_date="2027-03-21T23:59:00-04:00", source_url=regard, organizer="REGARD Festival", summary="The 2027 REGARD International Short Film Festival in Saguenay.", subfields=["Short Film","Film Festivals"], record_kind="event", type="festival", age_band="Public audiences and film industry", education_levels=["open","professional"], city="Saguenay", province="Québec", country="Canada", venue="Festival venues", series_title="REGARD Festival 2027", series_role="parent", calendar_stage="festival run", source_language="en", source_languages=["en","fr"]))

A(W(config=CONFIG, id="tiff-2027-film-submissions-watch", title="Toronto International Film Festival 2027 film submissions watch", marker="2027-02-01T00:00:00-05:00", source_url="https://tiff.net/submissions", organizer="Toronto International Film Festival", summary="The 2027 film-submission cycle is not yet officially dated.", subfields=["Film","Film Festivals"], opportunity_kind="film submission", age_band="Eligible filmmakers", education_levels=["professional"], recurrence_note="Annual TIFF submission cycle."))
A(W(config=CONFIG, id="tiff-2027-festival-watch", title="Toronto International Film Festival 2027 watch", marker="2027-09-01T00:00:00-04:00", source_url="https://tiff.net/about-the-festival", organizer="Toronto International Film Festival", summary="The 2027 festival dates are not yet officially announced.", subfields=["Film","Film Festivals"], record_kind="event", type="festival", age_band="Public audiences and film industry", education_levels=["open","professional"], city="Toronto", province="Ontario", country="Canada", venue="Toronto venues", recurrence_note="Annual September festival."))
A(W(config=CONFIG, id="tiff-next-wave-2027-watch", title="TIFF Next Wave 2027 watch", marker="2027-04-01T00:00:00-04:00", source_url="https://tiff.net/nextwave", organizer="Toronto International Film Festival", summary="The next TIFF Next Wave youth-film cycle is not yet officially dated.", subfields=["Youth Film","Film Festivals"], opportunity_kind="youth film program", age_band="Youth audience and emerging filmmakers", education_levels=["secondary","undergraduate"], recurrence_note="Annual youth-oriented TIFF program."))
A(W(config=CONFIG, id="plural-plus-youth-video-festival-2027-watch", title="PLURAL+ Youth Video Festival 2027 watch", marker="2027-05-01T00:00:00-04:00", source_url="https://pluralplus.unaoc.org/", organizer="United Nations Alliance of Civilizations and International Organization for Migration", summary="The 2027 youth-video call has not yet been officially published.", subfields=["Youth Video","Migration Media","Social-Issue Media"], opportunity_kind="youth video competition", age_band="Young filmmakers under the program rules", education_levels=["secondary","undergraduate"], recurrence_note="Annual international youth-video program."))

# Academic and professional media / communication.
scms = "https://www.cmstudies.org/page/SCMS2027"
A(R(config=CONFIG, id="scms-2027-cfp-deadline", title="Society for Cinema and Media Studies 2027 CFP deadline", date="2026-08-28T17:00:00-05:00", source_url=scms, organizer="Society for Cinema and Media Studies", summary="Deadline for proposals to the 2027 SCMS conference in Montréal.", subfields=["Cinema Studies","Media Studies","Academic Conference"], opportunity_kind="conference proposal", age_band="Graduate students, scholars, and media researchers", education_levels=["graduate","professional"], participation_unit="individual or panel", access_route="conference proposal system", submission_url=scms, parent_id="scms-2027-conference", series_title="SCMS 2027", series_role="child", calendar_stage="proposal closing", timezone="America/Chicago", date_precision="exact", time_precision="exact"))
A(R(config=CONFIG, id="scms-2027-conference", title="Society for Cinema and Media Studies 2027 Conference", date="2027-03-17T00:00:00-04:00", end_date="2027-03-20T23:59:00-04:00", source_url=scms, organizer="Society for Cinema and Media Studies", summary="SCMS 2027 in Montréal.", subfields=["Cinema Studies","Media Studies","Academic Conference"], record_kind="event", type="conference", age_band="Graduate students, scholars, and media researchers", education_levels=["graduate","professional"], city="Montréal", province="Québec", country="Canada", venue="Montréal conference venue", series_title="SCMS 2027", series_role="parent", calendar_stage="conference"))

ica = "https://www.icahdq.org/page/ICA2027"
A(R(config=CONFIG, id="ica-2027-cfp-deadline", title="International Communication Association 2027 submission deadline", date="2026-11-03T12:00:00-05:00", source_url=ica, organizer="International Communication Association", summary="Noon Eastern deadline for submissions to ICA 2027 in Glasgow.", subfields=["Communication Studies","Media Studies","Academic Conference"], opportunity_kind="conference submission", age_band="Graduate students, scholars, and communication researchers", education_levels=["graduate","professional"], participation_unit="individual or panel", access_route="conference submission system", submission_url=ica, parent_id="ica-2027-conference", series_title="ICA 2027", series_role="child", calendar_stage="submission closing"))
A(R(config=CONFIG, id="ica-2027-conference", title="International Communication Association 2027 Conference", date="2027-06-03T00:00:00+01:00", end_date="2027-06-07T23:59:00+01:00", source_url=ica, organizer="International Communication Association", summary="ICA 2027 in Glasgow.", subfields=["Communication Studies","Media Studies","Academic Conference"], record_kind="event", type="conference", age_band="Graduate students, scholars, and communication researchers", education_levels=["graduate","professional"], city="Glasgow", country="United Kingdom", venue="Glasgow conference venue", timezone="Europe/London", series_title="ICA 2027", series_role="parent", calendar_stage="conference"))

caj = "https://caj.ca/conference/"
A(R(config=CONFIG, id="caj-2027-session-proposal-deadline", title="Canadian Association of Journalists 2027 session-proposal deadline", date="2026-10-31T00:00:00-04:00", source_url=caj, organizer="Canadian Association of Journalists", summary="Deadline for session proposals for the 2027 national journalism conference in Winnipeg.", subfields=["Journalism","News Media","Professional Conference"], opportunity_kind="conference session proposal", age_band="Journalists, educators, and media professionals", education_levels=["educator","professional"], participation_unit="individual or group", access_route="proposal submission", submission_url=caj, parent_id="caj-2027-conference", series_title="CAJ 2027", series_role="child", calendar_stage="session proposal closing"))
A(R(config=CONFIG, id="caj-2027-conference", title="Canadian Association of Journalists 2027 Conference", date="2027-05-21T00:00:00-05:00", end_date="2027-05-22T23:59:00-05:00", source_url=caj, organizer="Canadian Association of Journalists", summary="The CAJ national journalism conference in Winnipeg.", subfields=["Journalism","News Media","Professional Conference"], record_kind="event", type="conference", age_band="Journalists, students, educators, and media professionals", education_levels=["undergraduate","graduate","educator","professional"], city="Winnipeg", province="Manitoba", country="Canada", venue="Winnipeg conference venue", timezone="America/Winnipeg", series_title="CAJ 2027", series_role="parent", calendar_stage="conference"))
A(W(config=CONFIG, id="caj-awards-2027-watch", title="Canadian Association of Journalists Awards 2027 watch", marker="2027-01-15T00:00:00-05:00", source_url="https://caj.ca/awards/", organizer="Canadian Association of Journalists", summary="The next awards submission cycle is not yet officially dated.", subfields=["Journalism","News Media","Awards"], opportunity_kind="journalism awards", age_band="Eligible Canadian journalists and news organizations", education_levels=["professional"], recurrence_note="Annual Canadian journalism awards."))

nspa = "https://studentpress.org/nspa/awards/"
for rid,title,stage in [
    ("nspa-literary-arts-2027-deadline","NSPA Literary Arts Magazine Pacemaker 2027 deadline","literary arts submission closing"),
    ("nspa-website-2027-deadline","NSPA Online Pacemaker 2027 deadline","website submission closing"),
    ("nspa-yearbook-2027-deadline","NSPA Yearbook Pacemaker 2027 deadline","yearbook submission closing"),
]:
    A(R(config=CONFIG,id=rid,title=title,date="2026-11-23T00:00:00-05:00",source_url=nspa,organizer="National Scholastic Press Association",summary="Submission deadline for the named 2027 scholastic-media Pacemaker category.",subfields=["Student Journalism","Scholastic Media"],opportunity_kind="student media award",age_band="Eligible middle-school, high-school, and college student media",education_levels=["secondary","college","undergraduate"],participation_unit="student publication",access_route="publication submission",prize_form="national recognition",submission_url=nspa,parent_id="nspa-2027-convention",series_title="NSPA 2027 awards",series_role="child",calendar_stage=stage))
A(R(config=CONFIG,id="nspa-innovation-2027-deadline",title="NSPA Innovation Pacemaker 2027 deadline",date="2027-01-08T00:00:00-05:00",source_url=nspa,organizer="National Scholastic Press Association",summary="Deadline for the Innovation Pacemaker recognizing student-media experimentation.",subfields=["Student Journalism","Media Innovation"],opportunity_kind="student media award",age_band="Eligible middle-school, high-school, and college student media",education_levels=["secondary","college","undergraduate"],participation_unit="student publication",access_route="publication submission",prize_form="national recognition",submission_url=nspa,parent_id="nspa-2027-convention",series_title="NSPA 2027 awards",series_role="child",calendar_stage="innovation submission closing"))
A(R(config=CONFIG,id="nspa-2027-convention",title="NSPA/JEA Spring National High School Journalism Convention 2027",date="2027-04-15T00:00:00-04:00",end_date="2027-04-18T23:59:00-04:00",source_url="https://studentpress.org/nspa/conventions/",organizer="National Scholastic Press Association and Journalism Education Association",summary="The official awards surface gives April 15–18, while a separate past-conventions surface gives April 15–17; the discrepancy is preserved.",subfields=["Student Journalism","Scholastic Media"],record_kind="event",type="conference",age_band="High-school journalists and advisers",education_levels=["secondary","educator"],city="Nashville",country="United States",venue="Convention venue",series_title="NSPA 2027 awards",series_role="parent",calendar_stage="convention and awards",source_inconsistency="Official NSPA surfaces conflict between April 15–18 and April 15–17, 2027."))

acp = "https://studentpress.org/acp/awards/"
A(R(config=CONFIG,id="acp-pacemaker-2027-deadline",title="Associated Collegiate Press 2027 Business, Online, and Yearbook deadline",date="2026-12-18T00:00:00-05:00",source_url=acp,organizer="Associated Collegiate Press",summary="Deadline for the current Business, Online, and Yearbook Pacemaker categories.",subfields=["College Journalism","Student Media"],opportunity_kind="collegiate media award",age_band="Eligible college and university student media",education_levels=["college","undergraduate"],participation_unit="student publication",access_route="publication submission",prize_form="national recognition",submission_url=acp,parent_id="acp-spring-conference-2027",series_title="ACP 2027 awards",series_role="child",calendar_stage="submission closing"))
A(R(config=CONFIG,id="acp-advertising-business-individual-awards-2027-deadline",title="ACP Advertising and Business Individual Awards 2027 deadline",date="2026-12-20T17:00:00-06:00",source_url=acp,organizer="Associated Collegiate Press",summary="Central Time deadline for Advertising and Business individual awards.",subfields=["College Journalism","Advertising","Media Business"],opportunity_kind="collegiate media award",age_band="Eligible college and university student media",education_levels=["college","undergraduate"],participation_unit="individual student",access_route="publication or adviser submission",prize_form="national recognition",submission_url=acp,parent_id="acp-spring-conference-2027",series_title="ACP 2027 awards",series_role="child",calendar_stage="submission closing",timezone="America/Chicago"))
A(R(config=CONFIG,id="acp-spring-conference-2027",title="Associated Collegiate Press Spring National College Media Conference 2027",date="2027-03-04T00:00:00-05:00",end_date="2027-03-06T23:59:00-05:00",source_url="https://studentpress.org/acp/conventions/",organizer="Associated Collegiate Press",summary="The 2027 ACP spring college-media conference.",subfields=["College Journalism","Student Media"],record_kind="event",type="conference",age_band="College journalists and advisers",education_levels=["college","undergraduate","educator"],city="Long Beach",country="United States",venue="Conference venue",series_title="ACP 2027 awards",series_role="parent",calendar_stage="conference and awards"))

A(R(config=CONFIG,id="jea-media-poster-2026-deadline",title="JEA 2026 Media Matters poster contest deadline",date="2026-09-14T23:59:00-05:00",source_url="https://jea.org/wp/blog/2026/08/03/media-matters-poster-contest/",organizer="Journalism Education Association",summary="U.S.-restricted poster contest for students in Grades 9–12; the current rules prohibit AI-generated art and charge a US$10 fee.",subfields=["Journalism","Visual Communication","Student Media"],opportunity_kind="poster contest",age_band="Grades 9-12 in the United States",exact_grades=[f"Grade {n}" for n in range(9,13)],education_levels=["secondary"],country="United States",participation_unit="individual student",access_route="direct submission",prize_form="recognition",institutional_restriction="United States eligibility only.",submission_url="https://jea.org/wp/blog/2026/08/03/media-matters-poster-contest/",calendar_stage="submission closing",timezone="America/Chicago",ai_rule="AI-generated art is prohibited."))
A(R(config=CONFIG,id="scholastic-journalism-week-2027",title="Scholastic Journalism Week 2027",date="2027-02-22T00:00:00-05:00",end_date="2027-02-26T23:59:00-05:00",source_url="https://jea.org/wp/scholastic-journalism-week/",organizer="Journalism Education Association",summary="Annual week of activities supporting student journalism and news literacy.",subfields=["Journalism","News Literacy","Student Media"],record_kind="event",type="festival",age_band="Students and journalism educators",education_levels=["secondary","educator"],country="United States",venue="Participating schools and online",calendar_stage="observance week"))
A(R(config=CONFIG,id="spj-jea-high-school-essay-2027-deadline",title="SPJ/JEA High School Essay Contest 2027 deadline",date="2027-02-21T23:59:00-06:00",source_url="https://www.spj.org/high-school-essay-contest/",organizer="Society of Professional Journalists and Journalism Education Association",summary="U.S.-restricted high-school essay contest on journalism and the First Amendment.",subfields=["Journalism","News Literacy","Student Writing"],opportunity_kind="journalism essay contest",age_band="United States high-school students",education_levels=["secondary"],country="United States",participation_unit="individual student",access_route="direct submission",institutional_restriction="United States high-school eligibility.",submission_url="https://www.spj.org/high-school-essay-contest/",calendar_stage="submission closing",timezone="America/Chicago"))

fetisov = "https://fjawards.com/"
A(R(config=CONFIG,id="fetisov-journalism-awards-2026-deadline",title="Fetisov Journalism Awards 2026 submission deadline",date="2026-09-15T23:59:00+00:00",source_url=fetisov,organizer="Fetisov Journalism Awards",summary="International deadline for eligible professional journalism entries.",subfields=["Journalism","Investigative Media","Professional Awards"],opportunity_kind="journalism award",age_band="Eligible professional journalists",education_levels=["professional"],participation_unit="journalist or team",access_route="direct nomination or submission under current rules",prize_form="international cash awards and recognition",submission_url=fetisov,calendar_stage="submission closing",timezone="UTC"))
A(W(config=CONFIG,id="fetisov-journalism-awards-2027-ceremony-watch",title="Fetisov Journalism Awards 2027 ceremony watch",marker="2027-04-01T00:00:00+00:00",source_url=fetisov,organizer="Fetisov Journalism Awards",summary="The organizer states that winners will be recognized in April 2027, but an exact ceremony date is not yet published.",subfields=["Journalism","Investigative Media","Professional Awards"],record_kind="event",type="ceremony",age_band="Finalists and professional journalism audience",education_levels=["professional"],parent_id="fetisov-journalism-awards-2026-deadline",series_title="Fetisov Journalism Awards 2026–27",series_role="child",calendar_stage="award ceremony",qualification_reasons=["exact-date-unconfirmed","time-unconfirmed"]))

A(R(config=CONFIG,id="cjf-emerging-news-voices-2026-deadline",title="CJF Emerging News Voices 2026 application deadline",date="2026-08-14T23:59:00-04:00",source_url="https://cjf-fjc.ca/emerging-news-voices/",organizer="Canadian Journalism Foundation",summary="Deadline for Canadian independent news creators and startups; selected projects may receive up to C$5,000 after completion.",subfields=["Journalism","Independent News","Media Entrepreneurship"],opportunity_kind="media innovation funding",age_band="Canadian independent news creators and startups",education_levels=["professional"],country="Canada",participation_unit="individual or startup",access_route="application",prize_form="up to C$5,000 after completion",application_url="https://cjf-fjc.ca/emerging-news-voices/",calendar_stage="application closing"))
for rid,title,sub in [
    ("cjf-indigenous-journalism-fellowship-2027-watch","CJF Indigenous Journalism Fellowship 2027 watch",["Journalism","Indigenous Media","Fellowship"]),
    ("cjf-tom-hanson-photojournalism-2027-watch","CJF Tom Hanson Photojournalism Award 2027 watch",["Photojournalism","Photography","Fellowship"]),
    ("cjf-bipoc-student-bursary-2027-watch","CJF BIPOC Student Bursary 2027 watch",["Journalism","Student Media","Bursary"]),
]:
    A(W(config=CONFIG,id=rid,title=title,marker="2027-01-15T00:00:00-05:00",source_url="https://cjf-fjc.ca/awards-fellowships/",organizer="Canadian Journalism Foundation",summary="The next cycle is legitimate but its exact 2027 deadline is not yet published.",subfields=sub,opportunity_kind="journalism fellowship or bursary",age_band="Eligible Canadian applicants under the program rules",education_levels=["undergraduate","professional"],recurrence_note="Annual Canadian Journalism Foundation program."))
A(W(config=CONFIG,id="hearst-journalism-awards-2026-27-cycle-watch",title="Hearst Journalism Awards Program 2026–27 cycle watch",marker="2026-09-01T00:00:00-04:00",source_url="https://www.hearstawards.org/",organizer="William Randolph Hearst Foundation",summary="The 2026–27 program comprises fourteen collegiate journalism competitions; exact category deadlines should be added as the official calendar is finalized.",subfields=["College Journalism","Student Media","Awards"],opportunity_kind="collegiate journalism competition series",age_band="Students at participating United States journalism schools",education_levels=["undergraduate"],country="United States",institutional_restriction="Participation through eligible United States journalism programs.",recurrence_note="Fourteen-category 2026–27 program."))
A(W(config=CONFIG,id="canadian-communication-association-2027-watch",title="Canadian Communication Association 2027 conference watch",marker="2027-06-01T00:00:00-04:00",source_url="https://acc-cca.ca/",organizer="Canadian Communication Association",summary="The 2027 conference and CFP are not yet officially dated.",subfields=["Communication Studies","Media Studies","Academic Conference"],record_kind="event",type="conference",age_band="Graduate students, scholars, and communication researchers",education_levels=["graduate","professional"],recurrence_note="Annual Congress-associated conference."))
A(W(config=CONFIG,id="film-and-media-studies-association-canada-2027-watch",title="Film and Media Studies Association of Canada 2027 conference watch",marker="2027-06-01T00:00:00-04:00",source_url="https://fmsac.ca/",organizer="Film and Media Studies Association of Canada",summary="The next FMSAC conference and CFP are not yet officially dated.",subfields=["Film Studies","Media Studies","Academic Conference"],record_kind="event",type="conference",age_band="Graduate students, scholars, and media researchers",education_levels=["graduate","professional"],recurrence_note="Annual Congress-associated conference."))
A(W(config=CONFIG,id="iamcr-2027-conference-watch",title="IAMCR 2027 conference watch",marker="2027-07-01T00:00:00-04:00",source_url="https://iamcr.org/",organizer="International Association for Media and Communication Research",summary="The 2027 conference and submission dates are not yet officially published.",subfields=["Communication Studies","Media Studies","Academic Conference"],record_kind="event",type="conference",age_band="Graduate students, scholars, and communication researchers",education_levels=["graduate","professional"],recurrence_note="Annual international conference."))
A(W(config=CONFIG,id="digra-2027-conference-watch",title="Digital Games Research Association 2027 conference watch",marker="2027-06-01T00:00:00-04:00",source_url="https://digra.org/",organizer="Digital Games Research Association",summary="The 2027 conference and CFP are not yet officially published.",subfields=["Game Studies","Digital Media","Academic Conference"],record_kind="event",type="conference",age_band="Graduate students, scholars, and game researchers",education_levels=["graduate","professional"],recurrence_note="Annual game-studies conference."))

# Coding, games, advertising, and media-information literacy.
codeart = "https://code-art.com/competitions/"
for rid,title,subs,grades in [
    ("codeart-codeyourself-2027-deadline","Code/Art CodeYourSelf 2027 deadline",["Coding","Digital Art","Youth Media"],list(range(3,13))),
    ("codeart-animated-art-2027-deadline","Code/Art Animated Art 2027 deadline",["Animation","Coding","Digital Art"],list(range(3,13))),
    ("codeart-game-design-2027-deadline","Code/Art Game Design 2027 deadline",["Game Design","Coding","Interactive Media"],list(range(3,13))),
    ("codeart-changemaker-2027-deadline","Code/Art Changemaker 2027 deadline",["Media Innovation","Coding","Video Pitch"],list(range(9,13))),
]:
    A(R(config=CONFIG,id=rid,title=title,date="2027-02-16T23:59:00-05:00",source_url=codeart,organizer="Code/Art",summary="Deadline for the named Code/Art competition for female-identifying or gender-nonbinary students. Changemaker uses teams and a video pitch; the other categories include coded creative work.",subfields=subs,opportunity_kind="student digital-media competition",age_band=f"Grades {grades[0]}-{grades[-1]}; female-identifying or gender-nonbinary students",exact_grades=[f"Grade {n}" for n in grades],education_levels=["elementary" if grades[0] <= 6 else "secondary","secondary"],participation_unit="individual or eligible team",access_route="direct submission",prize_form="awards and recognition",submission_url=codeart,calendar_stage="submission closing"))

ggj = "https://globalgamejam.org/news/ggj-2027-dates"
A(R(config=CONFIG,id="global-game-jam-2027-site-registration",title="Global Game Jam 2027 site registration opens",date="2026-11-01T00:00:00-04:00",source_url=ggj,organizer="Global Game Jam",summary="Opening of registration for organizations hosting official GGJ 2027 sites.",subfields=["Game Design","Interactive Media","Community Creation"],opportunity_kind="game-jam host registration",age_band="Eligible host organizations",education_levels=["educator","professional"],participation_unit="host organization",access_route="site registration",registration_url=ggj,parent_id="global-game-jam-2027",series_title="Global Game Jam 2027",series_role="child",calendar_stage="host-site registration opening"))
A(R(config=CONFIG,id="global-game-jam-2027-jammer-registration",title="Global Game Jam 2027 participant registration opens",date="2026-12-01T00:00:00-05:00",source_url=ggj,organizer="Global Game Jam",summary="Opening of participant registration for GGJ 2027 sites.",subfields=["Game Design","Interactive Media","Community Creation"],opportunity_kind="game-jam registration",age_band="Participants under local site rules",education_levels=["secondary","undergraduate","graduate","professional","open"],participation_unit="individual participant",access_route="local site registration",registration_url=ggj,parent_id="global-game-jam-2027",series_title="Global Game Jam 2027",series_role="child",calendar_stage="participant registration opening"))
A(R(config=CONFIG,id="global-game-jam-2027",title="Global Game Jam 2027",date="2027-01-25T00:00:00-05:00",end_date="2027-01-31T23:59:00-05:00",source_url=ggj,organizer="Global Game Jam",summary="Worldwide week of collaborative game creation through registered local and online sites.",subfields=["Game Design","Interactive Media","Community Creation"],record_kind="event",type="festival",age_band="Participants under local site rules",education_levels=["secondary","undergraduate","graduate","professional","open"],venue="Registered local and online sites",series_title="Global Game Jam 2027",series_role="parent",calendar_stage="jam week"))

igf = "https://igf.com/submissions"
A(R(config=CONFIG,id="igf-2027-fee-waiver-deadline",title="Independent Games Festival 2027 fee-waiver deadline",date="2026-09-07T23:59:00-07:00",source_url=igf,organizer="Independent Games Festival",summary="Deadline to request an entry-fee waiver for the 2027 IGF competition.",subfields=["Game Design","Independent Games","Professional Awards"],opportunity_kind="fee-waiver request",age_band="Independent game developers and student developers",education_levels=["undergraduate","professional"],participation_unit="developer or team",access_route="fee-waiver request",application_url=igf,parent_id="igf-2027",series_title="Independent Games Festival 2027",series_role="child",calendar_stage="fee-waiver closing",timezone="America/Los_Angeles"))
A(R(config=CONFIG,id="igf-2027-submission-deadline",title="Independent Games Festival 2027 submission deadline",date="2026-09-13T23:59:00-07:00",source_url=igf,organizer="Independent Games Festival",summary="Deadline for general and student game submissions; current fees are US$75 general and US$25 student unless waived.",subfields=["Game Design","Independent Games","Professional Awards"],opportunity_kind="game competition",age_band="Independent game developers and student developers",education_levels=["undergraduate","professional"],participation_unit="developer or team",access_route="direct submission",prize_form="festival awards and recognition",submission_url=igf,parent_id="igf-2027",series_title="Independent Games Festival 2027",series_role="child",calendar_stage="submission closing",timezone="America/Los_Angeles"))
A(R(config=CONFIG,id="igf-2027-pavilion",title="Independent Games Festival 2027 pavilion",date="2027-03-02T00:00:00-08:00",end_date="2027-03-04T23:59:00-08:00",source_url=igf,organizer="Independent Games Festival",summary="IGF pavilion during GDC 2027, within the March 1–5 conference week.",subfields=["Game Design","Independent Games","Professional Awards"],record_kind="event",type="exhibition",age_band="Selected developers and GDC attendees",education_levels=["undergraduate","professional"],city="San Francisco",country="United States",venue="Game Developers Conference",parent_id="igf-2027",series_title="Independent Games Festival 2027",series_role="child",calendar_stage="pavilion",timezone="America/Los_Angeles"))
A(R(config=CONFIG,id="igf-2027",title="Independent Games Festival Awards 2027",date="2027-03-03T00:00:00-08:00",source_url=igf,organizer="Independent Games Festival",summary="IGF awards ceremony during GDC 2027.",subfields=["Game Design","Independent Games","Professional Awards"],record_kind="event",type="ceremony",age_band="Finalists, developers, and GDC attendees",education_levels=["undergraduate","professional"],city="San Francisco",country="United States",venue="Game Developers Conference",series_title="Independent Games Festival 2027",series_role="parent",calendar_stage="award ceremony",timezone="America/Los_Angeles"))

breakthrough = "https://breakthroughjuniorchallenge.org/"
A(R(config=CONFIG,id="breakthrough-junior-challenge-2026-submission",title="Breakthrough Junior Challenge 2026 submission deadline",date="2026-09-15T23:59:00-07:00",source_url=breakthrough,organizer="Breakthrough Prize Foundation",summary="Worldwide deadline for ages 13–18 to submit a short explanatory science video.",subfields=["Science Communication","Video","Youth Media"],opportunity_kind="science video competition",age_band="Ages 13-18 worldwide",education_levels=["secondary"],participation_unit="individual student",access_route="direct submission",prize_form="US$250,000 scholarship, US$50,000 teacher award, and US$100,000 school laboratory",submission_url=breakthrough,parent_id="breakthrough-junior-challenge-2026-results",series_title="Breakthrough Junior Challenge 2026",series_role="child",calendar_stage="submission closing",timezone="America/Los_Angeles"))
A(R(config=CONFIG,id="breakthrough-junior-challenge-2026-peer-review",title="Breakthrough Junior Challenge 2026 peer-review deadline",date="2026-09-30T00:00:00-07:00",source_url=breakthrough,organizer="Breakthrough Prize Foundation",summary="Peer-review stage deadline for entrants in the 2026 challenge.",subfields=["Science Communication","Video","Peer Review"],opportunity_kind="competition peer review",age_band="Ages 13-18 entrants",education_levels=["secondary"],participation_unit="entrant",access_route="required post-submission peer review",parent_id="breakthrough-junior-challenge-2026-results",series_title="Breakthrough Junior Challenge 2026",series_role="child",calendar_stage="peer-review closing",timezone="America/Los_Angeles"))
A(R(config=CONFIG,id="breakthrough-junior-challenge-2026-results",title="Breakthrough Junior Challenge 2026 finalist and popular-vote results",date="2026-12-10T00:00:00-08:00",source_url=breakthrough,organizer="Breakthrough Prize Foundation",summary="Scheduled finalist and popular-vote result stage for the 2026 challenge.",subfields=["Science Communication","Video","Youth Media"],record_kind="event",type="ceremony",age_band="Ages 13-18 entrants and public audience",education_levels=["secondary","open"],participation_unit="selected finalist",access_route="selection from competition",prize_form="US$250,000 scholarship, teacher award, and school laboratory",series_title="Breakthrough Junior Challenge 2026",series_role="parent",calendar_stage="results announcement",timezone="America/Los_Angeles"))

nsac = "https://www.aaf.org/Public/Programs/College_Chapter/NSAC.aspx"
A(R(config=CONFIG,id="nsac-2027-plans-book-deadline",title="National Student Advertising Competition 2027 plans-book deadline",date="2027-03-25T15:00:00-04:00",source_url=nsac,organizer="American Advertising Federation",summary="Plans-book deadline for participating university teams in the 2027 National Student Advertising Competition.",subfields=["Advertising","Strategic Communication","Student Media"],opportunity_kind="advertising case competition",age_band="Participating university students",education_levels=["undergraduate"],country="United States",participation_unit="institutional student team",access_route="participating AAF college chapter",institutional_restriction="Participation through eligible university teams.",submission_url=nsac,parent_id="nsac-2027-national-final",series_title="NSAC 2027",series_role="child",calendar_stage="plans-book submission closing"))
A(R(config=CONFIG,id="nsac-2027-national-final",title="National Student Advertising Competition 2027 national final",date="2027-06-04T00:00:00-07:00",source_url=nsac,organizer="American Advertising Federation",summary="National final in Anaheim for qualifying university teams.",subfields=["Advertising","Strategic Communication","Student Media"],record_kind="event",type="contest",age_band="Qualifying university student teams",education_levels=["undergraduate"],city="Anaheim",country="United States",venue="AAF national conference venue",participation_unit="qualifying institutional team",access_route="regional qualification",series_title="NSAC 2027",series_role="parent",calendar_stage="national final",timezone="America/Los_Angeles"))

A(R(config=CONFIG,id="cannes-lions-2027",title="Cannes Lions International Festival of Creativity 2027",date="2027-06-21T00:00:00+02:00",end_date="2027-06-25T23:59:00+02:00",source_url="https://www.canneslions.com/festival",organizer="Cannes Lions",summary="The 2027 international advertising and creative-communications festival.",subfields=["Advertising","Creative Communication","Professional Media"],record_kind="event",type="festival",age_band="Advertising, design, media, and communications professionals and students",education_levels=["undergraduate","professional"],city="Cannes",country="France",venue="Palais des Festivals and associated venues",timezone="Europe/Paris",calendar_stage="festival run"))
A(R(config=CONFIG,id="unesco-global-media-information-literacy-week-2026",title="UNESCO Global Media and Information Literacy Week 2026",date="2026-10-24T00:00:00-04:00",end_date="2026-10-31T23:59:00-04:00",source_url="https://www.unesco.org/en/media-information-literacy/week",organizer="UNESCO",summary="Annual global observance promoting media and information literacy, critical engagement with information, and public programming.",subfields=["Media and Information Literacy","News Literacy","Digital Citizenship"],record_kind="event",type="festival",age_band="Public, educators, students, institutions, and civil society",education_levels=["elementary","secondary","undergraduate","graduate","educator","professional","open"],venue="Worldwide and online",calendar_stage="observance week"))
A(W(config=CONFIG,id="young-ones-student-awards-2027-watch",title="The One Club Young Ones Student Awards 2027 watch",marker="2026-09-01T00:00:00-04:00",source_url="https://www.oneclub.org/awards/youngones/",organizer="The One Club for Creativity",summary="The 2027 student creative-communications competition is expected to open in September 2026, but the exact opening and deadline are not yet published.",subfields=["Advertising","Design","Student Media"],opportunity_kind="student creative competition",age_band="Eligible college and university students",education_levels=["college","undergraduate"],recurrence_note="Annual student awards cycle."))
A(W(config=CONFIG,id="dandad-new-blood-awards-2027-watch",title="D&AD New Blood Awards 2027 watch",marker="2027-01-01T00:00:00-05:00",source_url="https://www.dandad.org/en/d-ad-new-blood-awards/",organizer="D&AD",summary="The 2027 New Blood student briefs and exact deadline are not yet officially published.",subfields=["Advertising","Design","Student Media"],opportunity_kind="student creative competition",age_band="Eligible students, recent graduates, and emerging creatives under current rules",education_levels=["college","undergraduate"],recurrence_note="Annual student brief competition."))
A(W(config=CONFIG,id="games-for-change-student-challenge-2027-watch",title="Games for Change Student Challenge 2026–27 watch",marker="2027-03-01T00:00:00-05:00",source_url="https://gamesforchange.org/studentchallenge/",organizer="Games for Change",summary="The current student game-design cycle is active, but an exact universal 2027 submission deadline was not recoverable from the official surface.",subfields=["Game Design","Social-Issue Media","Youth Media"],opportunity_kind="student game-design challenge",age_band="Middle- and high-school students under current regional rules",education_levels=["secondary"],recurrence_note="Annual student game-design program."))

cross_tags = {
    "soulpepper-medusa-2026": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Theatre Media","Myth Adaptation","Creator-Present"]},
    "soulpepper-medusa-talkback-2026-07-08": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Theatre Media","Creator-Present","Audience Dialogue"]},
    "neuroethics-essay-contest-2026": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Science Communication","Video"]},
    "legion-video-contest-2026": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Video","Documentary","Remembrance Media"]},
    "capture-ton-patrimoine-2027": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Photography","Heritage Media"]},
    "lance-ton-balado-2027": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Podcasting","Audio Storytelling"]},
    "canadian-literature-graphic-autobiography-2027": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Comics","Graphic Narrative"]},
    "carkner-labour-history-media-2027-watch": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Multimedia","Labour History Media"]},
    "oral-history-multimedia-award-2027": {"subjects":["Media Literacy"],"topics":["media-literacy"],"media_literacy_subfields":["Multimedia","Oral History Media"]},
}

exclusions = [
    {"title":"Unannounced 2027 TIFF, PLURAL+, CAJ award, CCA, FMSAC, IAMCR, DiGRA, Young Ones, D&AD, and Games for Change dates","reason":"Retained as qualified annual watches rather than assigned invented deadlines."},
    {"title":"United States-restricted scholastic journalism contests","reason":"Included only with explicit geographic and institutional restrictions; not represented as generally Canada-eligible."},
    {"title":"Film-festival last-minute phases without a recoverable date","reason":"Preserved as stage-specific watch records rather than omitted or silently dated."},
    {"title":"Existing canonical media-adjacent records","reason":"Cross-tagged without changing stable IDs, original _src values, or source lineage."},
]

assert len(records) == 73, f"Expected 73 Set 5 records, found {len(records)}"
apply_import(root=ROOT, config=CONFIG, records=records, cross_tags=cross_tags, exclusions=exclusions)
