#!/usr/bin/env python3
"""Idempotently import Polymythcal Set 6 — Interdisciplinary / General.

Covers major scholarships, leadership programs, innovation challenges,
entrepreneurship, research dissemination, science fairs, and broad academic or
public-impact opportunities that do not fit one of the five subject fields.
"""
from pathlib import Path
from polymythcal_set_import_common import make_record as R, make_watch as W, apply_import

ROOT = Path(__file__).resolve().parents[1]
CONFIG = {
    "src": "manual-polymythcal-interdisciplinary-set6-2026-08-13",
    "research_set": "6-Interdisciplinary-General",
    "checked": "2026-08-13T20:08:00-04:00",
    "domain_label": "Interdisciplinary",
    "topic_slug": "interdisciplinary",
    "set_tag": "Set 6",
    "entry_family": "interdisciplinary",
    "field_name": "interdisciplinary_domains",
    "metadata_key": "polymythcal_interdisciplinary_set6_update_2026_08_13",
    "sources_metadata_key": "polymythcal_interdisciplinary_set6_2026_08_13",
    "research_filename": "polymythcal-research-set-6-interdisciplinary-2026-08-13.json",
    "research_dirname": "polymythcal-set6-interdisciplinary-2026-08-13",
    "ledger_schema": "polymythcal-interdisciplinary-set6-research-ledger-v1",
    "cl_ids": [f"CL-WEB-{n}" for n in range(220, 228)],
    "ledger_notes": [
        "Broad scholarships, leadership programs, research dissemination, innovation, entrepreneurship, and public-impact challenges are indexed independently.",
        "Application openings, deadlines, selection stages, summits, conferences, and award periods remain linked but distinct.",
        "Exact grade, age, citizenship, nomination, institutional, and team requirements remain visible.",
        "Unannounced annual cycles remain qualified watches; stale current-cycle text is not rolled forward as fact.",
    ],
}

records = []
def A(event): records.append(event)

# Major Canadian scholarships and leadership programs.
loran = "https://loranscholar.ca/becoming-a-scholar/"
A(R(config=CONFIG,id="loran-2027-applications-open",title="Loran Award 2027 applications open",date="2026-09-09T00:00:00-04:00",source_url=loran,organizer="Loran Scholars Foundation",summary="Opening of applications for the 2027 Loran Award cycle.",subfields=["Scholarship","Leadership","Community Service"],opportunity_kind="undergraduate scholarship",age_band="Eligible Canadian high-school and CEGEP students under current rules",education_levels=["secondary","CEGEP"],country="Canada",participation_unit="individual applicant",access_route="direct application",application_url=loran,parent_id="loran-2027-application-deadline",series_title="Loran Award 2027",series_role="child",calendar_stage="applications opening"))
A(R(config=CONFIG,id="loran-2027-application-deadline",title="Loran Award 2027 application deadline",date="2026-10-15T12:00:00-04:00",source_url=loran,organizer="Loran Scholars Foundation",summary="Noon Eastern deadline for the 2027 Loran Award.",subfields=["Scholarship","Leadership","Community Service"],opportunity_kind="undergraduate scholarship",age_band="Eligible Canadian high-school and CEGEP students under current rules",education_levels=["secondary","CEGEP"],country="Canada",participation_unit="individual applicant",access_route="direct application",prize_form="renewable undergraduate scholarship, mentorship, and experiential support",application_url=loran,series_title="Loran Award 2027",series_role="parent",calendar_stage="application closing"))

terry = "https://terryfoxawards.ca/applicant-information/"
A(R(config=CONFIG,id="terry-fox-humanitarian-award-2027-open",title="Terry Fox Humanitarian Award 2027 applications open",date="2026-11-01T00:00:00-07:00",source_url=terry,organizer="Terry Fox Humanitarian Award Program",summary="Opening of the 2027 application cycle.",subfields=["Scholarship","Humanitarian Service","Leadership"],opportunity_kind="undergraduate scholarship",age_band="Eligible Canadian graduating secondary students and current first-year postsecondary students",education_levels=["secondary","college","undergraduate"],country="Canada",participation_unit="individual applicant",access_route="direct application",application_url=terry,parent_id="terry-fox-humanitarian-award-2027-deadline",series_title="Terry Fox Humanitarian Award 2027",series_role="child",calendar_stage="applications opening",timezone="America/Vancouver"))
A(R(config=CONFIG,id="terry-fox-humanitarian-award-2027-deadline",title="Terry Fox Humanitarian Award 2027 application deadline",date="2026-12-01T23:59:00-08:00",source_url=terry,organizer="Terry Fox Humanitarian Award Program",summary="Pacific Time deadline for the 2027 award cycle.",subfields=["Scholarship","Humanitarian Service","Leadership"],opportunity_kind="undergraduate scholarship",age_band="Eligible Canadian graduating secondary students and current first-year postsecondary students",education_levels=["secondary","college","undergraduate"],country="Canada",participation_unit="individual applicant",access_route="direct application",prize_form="renewable scholarship",application_url=terry,series_title="Terry Fox Humanitarian Award 2027",series_role="parent",calendar_stage="application closing",timezone="America/Vancouver"))

schulich = "https://schulichleaders.com/application/"
A(R(config=CONFIG,id="schulich-leader-scholarships-2027-school-nomination",title="Schulich Leader Scholarships 2027 school-nomination deadline",date="2027-01-27T00:00:00-05:00",source_url=schulich,organizer="Schulich Foundation",summary="Deadline for Canadian secondary schools and CEGEPs to nominate candidates.",subfields=["Scholarship","STEM","Leadership"],opportunity_kind="undergraduate STEM scholarship",age_band="Canadian graduating high-school and CEGEP students",education_levels=["secondary","CEGEP"],country="Canada",participation_unit="school nominee",access_route="school nomination",prize_form="major undergraduate STEM scholarship",institutional_restriction="A school or CEGEP nomination is required.",registration_url=schulich,parent_id="schulich-leader-scholarships-2027-offer-period",series_title="Schulich Leader Scholarships 2027",series_role="child",calendar_stage="school nomination closing"))
A(R(config=CONFIG,id="schulich-leader-scholarships-2027-nominee-application",title="Schulich Leader Scholarships 2027 nominee-application deadline",date="2027-02-17T00:00:00-05:00",source_url=schulich,organizer="Schulich Foundation",summary="Deadline for nominated students to complete the 2027 application.",subfields=["Scholarship","STEM","Leadership"],opportunity_kind="undergraduate STEM scholarship",age_band="Nominated Canadian graduating high-school and CEGEP students",education_levels=["secondary","CEGEP"],country="Canada",participation_unit="individual nominee",access_route="application after school nomination",prize_form="major undergraduate STEM scholarship",institutional_restriction="Only school-nominated students may apply.",application_url=schulich,parent_id="schulich-leader-scholarships-2027-offer-period",series_title="Schulich Leader Scholarships 2027",series_role="child",calendar_stage="nominee application closing"))
A(R(config=CONFIG,id="schulich-leader-scholarships-2027-offer-period",title="Schulich Leader Scholarships 2027 offer period",date="2027-03-08T00:00:00-05:00",end_date="2027-06-15T23:59:00-04:00",source_url=schulich,organizer="Schulich Foundation",summary="Official offer period for participating universities to make 2027 Schulich Leader Scholarship offers.",subfields=["Scholarship","STEM","Leadership"],record_kind="event",type="ceremony",age_band="Nominated applicants and participating Canadian universities",education_levels=["secondary","CEGEP"],country="Canada",participation_unit="selected nominee",access_route="selection by participating universities",prize_form="major undergraduate STEM scholarship",series_title="Schulich Leader Scholarships 2027",series_role="parent",calendar_stage="offer period"))

mccall = "https://mccallmacbainscholars.org/apply/"
A(R(config=CONFIG,id="mccall-macbain-2027-international-deadline",title="McCall MacBain Scholars 2027 international application deadline",date="2026-08-19T16:00:00-04:00",source_url=mccall,organizer="McCall MacBain Scholarships",summary="Eastern Time deadline for applicants outside Canada and the United States.",subfields=["Graduate Scholarship","Leadership","Interdisciplinary Study"],opportunity_kind="graduate scholarship",age_band="Eligible graduate-program applicants outside Canada and the United States",education_levels=["undergraduate","graduate"],participation_unit="individual applicant",access_route="direct application with references",prize_form="fully funded graduate scholarship and leadership program",application_url=mccall,parent_id="mccall-macbain-2027-canada-us-deadline",series_title="McCall MacBain Scholars 2027",series_role="child",calendar_stage="international application closing"))
A(R(config=CONFIG,id="mccall-macbain-2027-canada-us-deadline",title="McCall MacBain Scholars 2027 Canada and United States deadline",date="2026-09-23T16:00:00-04:00",source_url=mccall,organizer="McCall MacBain Scholarships",summary="Eastern Time deadline for applicants in Canada and the United States, including Canadians abroad under the current rules.",subfields=["Graduate Scholarship","Leadership","Interdisciplinary Study"],opportunity_kind="graduate scholarship",age_band="Eligible graduate-program applicants in Canada and the United States",education_levels=["undergraduate","graduate"],participation_unit="individual applicant",access_route="direct application with references",prize_form="fully funded graduate scholarship and leadership program",application_url=mccall,series_title="McCall MacBain Scholars 2027",series_role="parent",calendar_stage="Canada/United States application closing"))

A(W(config=CONFIG,id="td-scholarships-community-leadership-2027-watch",title="TD Scholarships for Community Leadership 2027 watch",marker="2026-11-01T00:00:00-04:00",source_url="https://www.td.com/ca/en/personal-banking/solutions/student-banking/community-leadership-scholarship-for-canadians",organizer="TD Bank Group",summary="The next Canadian community-leadership scholarship cycle is legitimate, but its exact 2027 deadline is not yet published.",subfields=["Scholarship","Community Leadership","Service"],opportunity_kind="undergraduate scholarship",age_band="Eligible Canadian secondary students",education_levels=["secondary"],country="Canada",recurrence_note="Annual Canadian scholarship cycle."))
A(W(config=CONFIG,id="shad-2027-program-watch",title="Shad 2027 program application watch",marker="2026-09-01T00:00:00-04:00",source_url="https://www.shad.ca/apply/",organizer="Shad Canada",summary="The 2027 application cycle for the Canadian STEAM and entrepreneurship program is not yet fully dated.",subfields=["STEAM","Entrepreneurship","Leadership","Summer Program"],opportunity_kind="summer enrichment program",age_band="Eligible Canadian secondary students",education_levels=["secondary"],country="Canada",recurrence_note="Annual summer program."))

# Innovation and entrepreneurship challenges.
diamond = "https://diamondchallenge.org/competition/"
A(R(config=CONFIG,id="diamond-challenge-2027-opens",title="Diamond Challenge 2027 submissions open",date="2026-09-16T00:00:00-04:00",source_url=diamond,organizer="University of Delaware Horn Entrepreneurship",summary="Opening of the 2027 global high-school entrepreneurship competition.",subfields=["Entrepreneurship","Social Innovation","Business Innovation"],opportunity_kind="youth entrepreneurship competition",age_band="Ages 14-18 worldwide",education_levels=["secondary"],participation_unit="team of 2-4 students",access_route="team registration and submission",registration_url=diamond,parent_id="diamond-challenge-summit-2027",series_title="Diamond Challenge 2027",series_role="child",calendar_stage="submissions opening"))
A(R(config=CONFIG,id="diamond-challenge-2027-deadline",title="Diamond Challenge 2027 submission deadline",date="2027-01-14T17:00:00-05:00",source_url=diamond,organizer="University of Delaware Horn Entrepreneurship",summary="Eastern Time deadline for business-innovation and social-innovation concepts.",subfields=["Entrepreneurship","Social Innovation","Business Innovation"],opportunity_kind="youth entrepreneurship competition",age_band="Ages 14-18 worldwide",education_levels=["secondary"],participation_unit="team of 2-4 students",access_route="team submission",prize_form="awards, mentoring, and summit participation",submission_url=diamond,parent_id="diamond-challenge-summit-2027",series_title="Diamond Challenge 2027",series_role="child",calendar_stage="submission closing"))
A(R(config=CONFIG,id="diamond-challenge-2027-advancing-teams",title="Diamond Challenge 2027 advancing teams announcement",date="2027-02-10T00:00:00-05:00",source_url=diamond,organizer="University of Delaware Horn Entrepreneurship",summary="Scheduled announcement of teams advancing from the first evaluation stage.",subfields=["Entrepreneurship","Social Innovation","Business Innovation"],record_kind="event",type="contest",age_band="Ages 14-18 entrants",education_levels=["secondary"],participation_unit="selected team",access_route="selection from submissions",parent_id="diamond-challenge-summit-2027",series_title="Diamond Challenge 2027",series_role="child",calendar_stage="advancing teams announcement"))
A(R(config=CONFIG,id="diamond-challenge-2027-finalists",title="Diamond Challenge 2027 finalist announcement",date="2027-03-09T00:00:00-05:00",source_url=diamond,organizer="University of Delaware Horn Entrepreneurship",summary="Scheduled finalist announcement for the 2027 Summit.",subfields=["Entrepreneurship","Social Innovation","Business Innovation"],record_kind="event",type="contest",age_band="Ages 14-18 entrants",education_levels=["secondary"],participation_unit="selected team",access_route="selection from advancing teams",parent_id="diamond-challenge-summit-2027",series_title="Diamond Challenge 2027",series_role="child",calendar_stage="finalist announcement"))
A(R(config=CONFIG,id="diamond-challenge-summit-2027",title="Diamond Challenge Summit 2027",date="2027-04-29T00:00:00-04:00",end_date="2027-04-30T23:59:00-04:00",source_url=diamond,organizer="University of Delaware Horn Entrepreneurship",summary="Final summit for selected global high-school entrepreneurship teams.",subfields=["Entrepreneurship","Social Innovation","Business Innovation"],record_kind="event",type="contest",age_band="Selected ages 14-18 teams",education_levels=["secondary"],city="Newark",country="United States",venue="University of Delaware",participation_unit="finalist team",access_route="selection through competition",prize_form="awards, mentoring, and recognition",series_title="Diamond Challenge 2027",series_role="parent",calendar_stage="summit and final"))

conrad = "https://www.conradchallenge.org/participate"
A(R(config=CONFIG,id="conrad-challenge-2026-27-activation-start",title="Conrad Challenge 2026–27 Activation Stage begins",date="2026-08-27T00:00:00-04:00",source_url=conrad,organizer="Conrad Foundation",summary="Beginning of the Activation Stage for the 2026–27 innovation challenge.",subfields=["Innovation","Entrepreneurship","STEM","Social Impact"],opportunity_kind="youth innovation competition",age_band="Eligible secondary-school students under current rules",education_levels=["secondary"],participation_unit="student team",access_route="team registration",registration_url=conrad,parent_id="conrad-innovation-summit-2027",series_title="Conrad Challenge 2026–27",series_role="child",calendar_stage="activation stage opening",source_inconsistency="The official source contains stale 2025–26 sub-lines alongside the 2026–27 timeline."))
A(R(config=CONFIG,id="conrad-challenge-2026-27-activation-deadline",title="Conrad Challenge 2026–27 Activation Stage deadline",date="2026-10-30T00:00:00-04:00",source_url=conrad,organizer="Conrad Foundation",summary="End of the Activation Stage and transition into the Innovation Stage.",subfields=["Innovation","Entrepreneurship","STEM","Social Impact"],opportunity_kind="youth innovation competition",age_band="Eligible secondary-school students under current rules",education_levels=["secondary"],participation_unit="student team",access_route="team registration and stage completion",registration_url=conrad,parent_id="conrad-innovation-summit-2027",series_title="Conrad Challenge 2026–27",series_role="child",calendar_stage="activation stage closing",source_inconsistency="The official source contains stale 2025–26 sub-lines alongside the 2026–27 timeline."))
A(R(config=CONFIG,id="conrad-challenge-2027-innovation-stage-deadline",title="Conrad Challenge 2027 Innovation Stage deadline",date="2027-01-08T00:00:00-05:00",source_url=conrad,organizer="Conrad Foundation",summary="Innovation Stage submission deadline; the current team fee is US$499.",subfields=["Innovation","Entrepreneurship","STEM","Social Impact"],opportunity_kind="youth innovation competition",age_band="Eligible secondary-school students under current rules",education_levels=["secondary"],participation_unit="student team",access_route="registered-team submission",prize_form="summit participation, awards, and recognition",submission_url=conrad,parent_id="conrad-innovation-summit-2027",series_title="Conrad Challenge 2026–27",series_role="child",calendar_stage="innovation stage closing",source_inconsistency="The official source contains stale 2025–26 sub-lines alongside the 2026–27 timeline."))
A(R(config=CONFIG,id="conrad-challenge-2027-finalists",title="Conrad Challenge 2027 finalist announcement",date="2027-02-26T19:00:00-06:00",source_url=conrad,organizer="Conrad Foundation",summary="Central Time announcement of finalist teams invited to the Innovation Summit.",subfields=["Innovation","Entrepreneurship","STEM","Social Impact"],record_kind="event",type="contest",age_band="Eligible secondary-school teams",education_levels=["secondary"],participation_unit="selected team",access_route="selection from Innovation Stage",parent_id="conrad-innovation-summit-2027",series_title="Conrad Challenge 2026–27",series_role="child",calendar_stage="finalist announcement",timezone="America/Chicago",source_inconsistency="The official source contains stale 2025–26 sub-lines alongside the 2026–27 timeline."))
A(R(config=CONFIG,id="conrad-innovation-summit-2027",title="Conrad Innovation Summit 2027",date="2027-04-21T00:00:00-05:00",end_date="2027-04-24T23:59:00-05:00",source_url=conrad,organizer="Conrad Foundation",summary="Finalist summit at Space Center Houston. Current participant pricing is US$499 per attendee by invitation.",subfields=["Innovation","Entrepreneurship","STEM","Social Impact"],record_kind="event",type="contest",age_band="Invited finalist teams",education_levels=["secondary"],city="Houston",country="United States",venue="Space Center Houston",participation_unit="finalist team",access_route="invitation after selection",prize_form="awards, recognition, and summit participation",series_title="Conrad Challenge 2026–27",series_role="parent",calendar_stage="summit and final",timezone="America/Chicago",source_inconsistency="The official source contains stale 2025–26 sub-lines alongside the 2026–27 timeline."))

A(W(config=CONFIG,id="earth-prize-2027-deadline-watch",title="The Earth Prize 2027 deadline watch",marker="2027-01-01T00:00:00-05:00",source_url="https://www.theearthprize.org/",organizer="The Earth Foundation",summary="Registration for the 2027 global environmental-sustainability competition is open to ages 13–19, but the detailed official timeline still shows the prior cycle and no dependable 2027 deadline is yet published.",subfields=["Environmental Innovation","Sustainability","Youth Research"],opportunity_kind="youth sustainability competition",age_band="Ages 13-19 worldwide",education_levels=["secondary"],source_inconsistency="The official site announces 2027 registration while its detailed timeline still describes the 2026 cycle.",recurrence_note="Annual global sustainability competition."))

tech = "https://technovationchallenge.org/get-involved/student-ambassadors/"
A(R(config=CONFIG,id="technovation-student-ambassador-2026-27-deadline",title="Technovation Student Ambassador 2026–27 application deadline",date="2026-09-06T23:59:00-04:00",source_url=tech,organizer="Technovation",summary="Worldwide deadline for Technovation alumnae ages 13–18 who completed at least one project and can serve one to two hours weekly from October through May.",subfields=["Technology","Leadership","Community Building","Youth Entrepreneurship"],opportunity_kind="student leadership program",age_band="Ages 13-18; Technovation alumnae worldwide",education_levels=["secondary"],participation_unit="individual applicant",access_route="alumna application",institutional_restriction="Applicant must have completed a Technovation project in a prior season.",application_url=tech,calendar_stage="application closing"))
A(W(config=CONFIG,id="technovation-girls-2026-27-season-watch",title="Technovation Girls 2026–27 competition watch",marker="2026-08-14T00:00:00-04:00",source_url="https://technovationchallenge.org/competition/",organizer="Technovation",summary="The organizer is preparing the 2026–27 global technology-and-entrepreneurship season, but the public competition page still lists 2025–26 registration and submission dates.",subfields=["Technology","Entrepreneurship","Community Problem Solving","Youth Innovation"],opportunity_kind="global youth technology competition",age_band="Girls and eligible gender-diverse participants ages 8-18 worldwide",education_levels=["elementary","secondary"],source_inconsistency="The official competition page still displays the 2025–26 timeline while the organization advertises the coming 2026–27 season.",recurrence_note="Annual global program."))

wharton = "https://globalyouth.wharton.upenn.edu/investment-competition/"
A(R(config=CONFIG,id="wharton-global-investment-competition-2026-27-registration",title="Wharton Global High School Investment Competition 2026–27 registration deadline",date="2026-09-11T17:00:00-04:00",source_url=wharton,organizer="Wharton Global Youth Program",summary="Main registration-page deadline for secondary-school investment teams. An FAQ snippet gives 4 p.m. while the main registration page gives 5 p.m.; the conflict is preserved.",subfields=["Finance","Investment","Team Strategy","Applied Economics"],opportunity_kind="high-school investment competition",age_band="Eligible secondary-school teams worldwide",education_levels=["secondary"],participation_unit="school-based team",access_route="adviser-led team registration",registration_url=wharton,calendar_stage="registration closing",source_inconsistency="Official surfaces conflict between 4:00 p.m. and 5:00 p.m. Eastern; the main registration page states 5:00 p.m."))

# Research dissemination and broad academic participation.
cwsf = "https://youthscience.ca/science-fairs/canada-wide-science-fair/"
A(R(config=CONFIG,id="canada-wide-science-fair-2027",title="Canada-Wide Science Fair 2027",date="2027-05-29T00:00:00-04:00",end_date="2027-06-05T23:59:00-04:00",source_url=cwsf,organizer="Youth Science Canada",summary="National fair in Hamilton for students qualifying through regional science fairs.",subfields=["Student Research","Science Fair","Innovation","Public Exhibition"],record_kind="event",type="festival",age_band="Grades 7-12 and CEGEP through regional qualification",exact_grades=[f"Grade {n}" for n in range(7,13)],education_levels=["secondary","CEGEP"],city="Hamilton",province="Ontario",country="Canada",venue="Hamilton venue",participation_unit="qualified student or team",access_route="regional fair qualification",prize_form="awards, scholarships, and national recognition",series_title="Canada-Wide Science Fair 2027",series_role="parent",calendar_stage="fair run"))
A(R(config=CONFIG,id="canada-wide-science-fair-2027-public-viewing-may30",title="Canada-Wide Science Fair 2027 public viewing — May 30",date="2027-05-30T00:00:00-04:00",source_url=cwsf,organizer="Youth Science Canada",summary="First listed public-viewing day for CWSF 2027.",subfields=["Student Research","Science Fair","Public Exhibition"],record_kind="event",type="exhibition",age_band="Public audience",education_levels=["open"],city="Hamilton",province="Ontario",country="Canada",venue="Hamilton venue",parent_id="canada-wide-science-fair-2027",series_title="Canada-Wide Science Fair 2027",series_role="child",calendar_stage="public viewing"))
A(R(config=CONFIG,id="canada-wide-science-fair-2027-public-viewing-june",title="Canada-Wide Science Fair 2027 public viewing — June 3–4",date="2027-06-03T00:00:00-04:00",end_date="2027-06-04T23:59:00-04:00",source_url=cwsf,organizer="Youth Science Canada",summary="Additional listed public-viewing period for CWSF 2027.",subfields=["Student Research","Science Fair","Public Exhibition"],record_kind="event",type="exhibition",age_band="Public audience",education_levels=["open"],city="Hamilton",province="Ontario",country="Canada",venue="Hamilton venue",parent_id="canada-wide-science-fair-2027",series_title="Canada-Wide Science Fair 2027",series_role="child",calendar_stage="public viewing"))

ncur = "https://www.cur.org/events-services/ncur/"
A(R(config=CONFIG,id="ncur-2027-submissions-open",title="NCUR 2027 submissions open",date="2026-09-09T00:00:00-04:00",source_url=ncur,organizer="Council on Undergraduate Research",summary="Opening of student presentation submissions for the 2027 National Conference on Undergraduate Research.",subfields=["Undergraduate Research","Research Communication","Academic Conference"],opportunity_kind="undergraduate conference submission",age_band="Undergraduate researchers",education_levels=["undergraduate"],participation_unit="individual or research team",access_route="abstract submission",submission_url=ncur,parent_id="ncur-2027-conference",series_title="NCUR 2027",series_role="child",calendar_stage="submissions opening"))
A(R(config=CONFIG,id="ncur-2027-submission-deadline",title="NCUR 2027 submission deadline",date="2026-12-04T00:00:00-05:00",source_url=ncur,organizer="Council on Undergraduate Research",summary="Closing date for student presentation submissions to NCUR 2027.",subfields=["Undergraduate Research","Research Communication","Academic Conference"],opportunity_kind="undergraduate conference submission",age_band="Undergraduate researchers",education_levels=["undergraduate"],participation_unit="individual or research team",access_route="abstract submission",submission_url=ncur,parent_id="ncur-2027-conference",series_title="NCUR 2027",series_role="child",calendar_stage="submission closing"))
A(R(config=CONFIG,id="ncur-2027-decisions-and-registration",title="NCUR 2027 decisions and registration open",date="2027-01-13T00:00:00-05:00",source_url=ncur,organizer="Council on Undergraduate Research",summary="Scheduled notification and registration-opening stage for NCUR 2027.",subfields=["Undergraduate Research","Research Communication","Academic Conference"],record_kind="event",type="conference",age_band="Submitting undergraduate researchers and advisers",education_levels=["undergraduate","educator"],participation_unit="accepted presenter or attendee",access_route="selection or conference registration",registration_url=ncur,parent_id="ncur-2027-conference",series_title="NCUR 2027",series_role="child",calendar_stage="decisions and registration opening"))
A(R(config=CONFIG,id="ncur-2027-early-bird-registration",title="NCUR 2027 early-bird registration deadline",date="2027-01-29T00:00:00-05:00",source_url=ncur,organizer="Council on Undergraduate Research",summary="Early-bird registration deadline for NCUR 2027.",subfields=["Undergraduate Research","Research Communication","Academic Conference"],opportunity_kind="conference registration",age_band="Accepted presenters, advisers, and attendees",education_levels=["undergraduate","educator"],participation_unit="individual registrant",access_route="conference registration",registration_url=ncur,parent_id="ncur-2027-conference",series_title="NCUR 2027",series_role="child",calendar_stage="early-bird registration closing"))
A(R(config=CONFIG,id="ncur-2027-conference",title="National Conference on Undergraduate Research 2027",date="2027-04-12T00:00:00-04:00",end_date="2027-04-14T23:59:00-04:00",source_url=ncur,organizer="Council on Undergraduate Research",summary="NCUR 2027 at DeVos Place in Grand Rapids, Michigan.",subfields=["Undergraduate Research","Research Communication","Academic Conference"],record_kind="event",type="conference",age_band="Undergraduate researchers, advisers, and academic audience",education_levels=["undergraduate","educator","professional"],city="Grand Rapids",country="United States",venue="DeVos Place Convention Center",series_title="NCUR 2027",series_role="parent",calendar_stage="conference"))

connectur = "https://www.cur.org/events-services/connectur/"
A(R(config=CONFIG,id="connectur-2027-submissions-open",title="ConnectUR 2027 submissions open",date="2026-11-04T00:00:00-05:00",source_url=connectur,organizer="Council on Undergraduate Research",summary="Opening of proposal submissions for ConnectUR 2027 professional-development programming.",subfields=["Undergraduate Research","Faculty Development","Academic Conference"],opportunity_kind="conference proposal",age_band="Faculty, staff, administrators, and undergraduate-research professionals",education_levels=["educator","professional"],participation_unit="individual or group",access_route="proposal submission",submission_url=connectur,parent_id="connectur-2027-onsite",series_title="ConnectUR 2027",series_role="child",calendar_stage="submissions opening"))
A(R(config=CONFIG,id="connectur-2027-submission-deadline",title="ConnectUR 2027 submission deadline",date="2027-01-15T00:00:00-05:00",source_url=connectur,organizer="Council on Undergraduate Research",summary="Proposal deadline for ConnectUR 2027.",subfields=["Undergraduate Research","Faculty Development","Academic Conference"],opportunity_kind="conference proposal",age_band="Faculty, staff, administrators, and undergraduate-research professionals",education_levels=["educator","professional"],participation_unit="individual or group",access_route="proposal submission",submission_url=connectur,parent_id="connectur-2027-onsite",series_title="ConnectUR 2027",series_role="child",calendar_stage="submission closing"))
A(R(config=CONFIG,id="connectur-2027-online",title="ConnectUR 2027 online conference",date="2027-06-22T00:00:00-04:00",end_date="2027-06-23T23:59:00-04:00",source_url=connectur,organizer="Council on Undergraduate Research",summary="Online component of ConnectUR 2027.",subfields=["Undergraduate Research","Faculty Development","Academic Conference"],record_kind="event",type="conference",age_band="Faculty, staff, administrators, and undergraduate-research professionals",education_levels=["educator","professional"],venue="Online",parent_id="connectur-2027-onsite",series_title="ConnectUR 2027",series_role="child",calendar_stage="online conference"))
A(R(config=CONFIG,id="connectur-2027-onsite",title="ConnectUR 2027 in Providence",date="2027-06-28T00:00:00-04:00",end_date="2027-06-30T23:59:00-04:00",source_url=connectur,organizer="Council on Undergraduate Research",summary="Onsite ConnectUR 2027 in Providence, Rhode Island.",subfields=["Undergraduate Research","Faculty Development","Academic Conference"],record_kind="event",type="conference",age_band="Faculty, staff, administrators, and undergraduate-research professionals",education_levels=["educator","professional"],city="Providence",country="United States",venue="Providence conference venue",series_title="ConnectUR 2027",series_role="parent",calendar_stage="onsite conference"))

A(R(config=CONFIG,id="cur-grant-dialogues-2027",title="CUR Grant Dialogues 2027",date="2027-02-09T10:00:00-05:00",end_date="2027-02-10T16:00:00-05:00",source_url="https://www.cur.org/events-services/dialogues/",organizer="Council on Undergraduate Research",summary="Virtual professional-development event on grant planning and undergraduate research, scheduled 10 a.m.–4 p.m. Eastern each day.",subfields=["Research Funding","Faculty Development","Undergraduate Research"],record_kind="event",type="conference",age_band="Faculty, staff, administrators, and research-development professionals",education_levels=["educator","professional"],venue="Online",calendar_stage="virtual event"))
A(R(config=CONFIG,id="undergraduate-research-week-2027",title="Undergraduate Research Week 2027",date="2027-04-19T00:00:00-04:00",end_date="2027-04-23T23:59:00-04:00",source_url="https://www.cur.org/events-services/undergraduate-research-week/",organizer="Council on Undergraduate Research",summary="Annual week recognizing undergraduate research and creative activity across disciplines.",subfields=["Undergraduate Research","Research Communication","Campus Events"],record_kind="event",type="festival",age_band="Undergraduate researchers, institutions, educators, and public audiences",education_levels=["undergraduate","educator","professional","open"],venue="Participating institutions and online",calendar_stage="observance week"))

A(W(config=CONFIG,id="global-undergraduate-awards-2027-watch",title="Global Undergraduate Awards 2027 watch",marker="2027-05-01T00:00:00-04:00",source_url="https://undergraduateawards.com/",organizer="The Global Undergraduate Awards",summary="The next worldwide undergraduate research and essay award cycle is legitimate, but its exact 2027 deadline is not yet published.",subfields=["Undergraduate Research","Academic Writing","International Awards"],opportunity_kind="undergraduate academic award",age_band="Eligible undergraduate students and recent graduates under current rules",education_levels=["undergraduate"],recurrence_note="Annual global awards cycle."))
A(W(config=CONFIG,id="sshrc-storytellers-challenge-2027-watch",title="SSHRC Storytellers Challenge 2027 watch",marker="2027-01-01T00:00:00-05:00",source_url="https://www.sshrc-crsh.gc.ca/society-societe/storytellers-jai_une_histoire_a_raconter/index-eng.aspx",organizer="Social Sciences and Humanities Research Council",summary="The next Canadian research-communication challenge is not yet officially dated.",subfields=["Research Communication","Social Sciences and Humanities","Public Scholarship"],opportunity_kind="student research-communication competition",age_band="Eligible Canadian postsecondary students",education_levels=["undergraduate","graduate"],country="Canada",recurrence_note="Annual bilingual Canadian challenge."))
A(W(config=CONFIG,id="hult-prize-2027-watch",title="Hult Prize 2027 cycle watch",marker="2026-09-01T00:00:00-04:00",source_url="https://www.hultprize.org/",organizer="Hult Prize Foundation",summary="The next global student social-enterprise competition cycle is not yet fully dated on the official surface.",subfields=["Social Entrepreneurship","Business Innovation","Global Challenges"],opportunity_kind="student social-enterprise competition",age_band="Eligible university and college students under current rules",education_levels=["college","undergraduate","graduate"],participation_unit="student team",recurrence_note="Annual global competition."))

cross_tags = {
    "breakthrough-junior-challenge-2026-submission": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Science Communication","Youth Scholarship","Research Explanation"]},
    "breakthrough-junior-challenge-2026-peer-review": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Science Communication","Peer Review","Youth Research"]},
    "breakthrough-junior-challenge-2026-results": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Science Communication","Youth Scholarship","Awards"]},
    "one-earth-young-filmmakers-2027-deadline": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Environmental Communication","Youth Innovation","Film"]},
    "one-earth-young-filmmakers-2027-premieres": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Environmental Communication","Public Exhibition","Film"]},
    "connecther-film-festival-2026-deadline": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Gender","Social Impact","Film"]},
    "codeart-changemaker-2027-deadline": {"subjects":["Interdisciplinary"],"topics":["interdisciplinary"],"interdisciplinary_domains":["Coding","Social Innovation","Video Pitch"]},
}

exclusions = [
    {"title":"TD, Shad, Earth Prize, Global Undergraduate Awards, SSHRC Storytellers, and Hult dates not yet announced","reason":"Retained as qualified watches rather than assigned projected deadlines."},
    {"title":"Technovation main 2026–27 deadline","reason":"The official competition surface still displays the prior cycle; only the confirmed Student Ambassador deadline is dated."},
    {"title":"Narrow single-discipline awards","reason":"Left in their governing subject set unless the program genuinely crosses multiple fields or is broadly general."},
    {"title":"Existing Set 5 interdisciplinary media opportunities","reason":"Cross-tagged without changing their stable IDs, original source identity, or provenance."},
]

assert len(records) == 42, f"Expected 42 Set 6 records, found {len(records)}"
apply_import(root=ROOT, config=CONFIG, records=records, cross_tags=cross_tags, exclusions=exclusions)
