from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from scripts.package_integrity import (
    MANIFEST_NAME,
    exclusive_output_lock,
    verify_file_member,
    write_verified_archive,
)
from scripts.package_selection import (
    collect_package_files,
    is_reconstruction_duplicate,
    selected_bytes_excluding,
)


def load_package_release_module():
    scripts_dir = Path(__file__).resolve().parent
    module_path = scripts_dir / "package-front-facing-mephistodata-release.py"
    spec = importlib.util.spec_from_file_location("package_front_facing_release", module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load package release module: {module_path}")
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(scripts_dir))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    return module


class PortableCoreLengthGateTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.release_module = load_package_release_module()

    def assertCoreLength(self, text: str, accepted: bool) -> None:
        if accepted:
            self.release_module.validate_portable_core_length(text)
        else:
            with self.assertRaisesRegex(ValueError, "UTF-16-unit"):
                self.release_module.validate_portable_core_length(text)

    def test_ascii_utf16_boundary(self) -> None:
        self.assertCoreLength("x" * 5000, True)
        self.assertCoreLength("x" * 5001, False)

    def test_multibyte_utf8_bytes_are_informational(self) -> None:
        accepted = "é" * 5000
        metrics = self.release_module.validate_portable_core_length(accepted)
        self.assertEqual(metrics["utf16_units"], 5000)
        self.assertEqual(metrics["utf8_bytes"], 10000)
        self.assertCoreLength("é" * 5001, False)

    def test_surrogate_pair_utf16_boundary(self) -> None:
        self.assertCoreLength("😀" * 2500, True)
        self.assertCoreLength(("😀" * 2500) + "x", False)


class PackageIntegrityTests(unittest.TestCase):
    def test_reserved_manifest_input_is_rejected(self) -> None:
        release = {
            "release_id": "test-audit39",
            "generated_at": "2026-07-24T22:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            stale_manifest = root / MANIFEST_NAME
            stale_manifest.write_text('{"release_id":"older-release"}\n', encoding="utf-8")
            with self.assertRaisesRegex(
                ValueError,
                "generated by the archive writer",
            ):
                write_verified_archive(
                    root,
                    root / "release.zip",
                    [stale_manifest],
                    release,
                    "test",
                )

    def test_archive_is_repeatable_and_self_verifying(self) -> None:
        release = {
            "release_id": "test-audit35",
            "generated_at": "2026-07-23T20:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / "nested").mkdir()
            (root / "alpha.txt").write_text("alpha\n", encoding="utf-8")
            (root / "nested" / "beta.json").write_text('{"beta":true}\n', encoding="utf-8")
            files = [root / "nested" / "beta.json", root / "alpha.txt"]
            first = root / "first.zip"
            second = root / "second.zip"
            result_one = write_verified_archive(root, first, files, release, "test")
            result_two = write_verified_archive(root, second, files, release, "test")

            self.assertEqual(result_one["archive_sha256"], result_two["archive_sha256"])
            self.assertEqual(first.read_bytes(), second.read_bytes())
            self.assertTrue(Path(str(first) + ".sha256").is_file())
            with zipfile.ZipFile(first) as archive:
                manifest = json.loads(archive.read(MANIFEST_NAME))
                self.assertEqual(manifest["file_count"], 2)
                self.assertEqual([row["path"] for row in manifest["files"]], ["alpha.txt", "nested/beta.json"])
                self.assertIsNone(archive.testzip())

    def test_writer_streams_without_whole_file_reads_or_duplicate_crc_pass(self) -> None:
        release = {
            "release_id": "test-audit46",
            "generated_at": "2026-07-26T12:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "large-enough-to-chunk.bin"
            source.write_bytes((b"streamed-package-data\n" * 65536) + b"done\n")
            output = root / "release.zip"

            with (
                patch.object(
                    Path,
                    "read_bytes",
                    side_effect=AssertionError("source file was read into memory"),
                ),
                patch.object(
                    zipfile.ZipFile,
                    "testzip",
                    side_effect=AssertionError("archive was inflated twice"),
                ),
            ):
                result = write_verified_archive(
                    root,
                    output,
                    [source],
                    release,
                    "streaming-test",
                )

            self.assertEqual(result["file_count"], 1)
            self.assertTrue(output.is_file())

    def test_writer_hashes_each_source_during_its_single_archive_write(self) -> None:
        release = {
            "release_id": "test-audit49",
            "generated_at": "2026-07-26T18:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source.bin"
            source.write_bytes(b"single-source-pass\n" * 65536)
            output = root / "release.zip"
            from scripts import package_integrity

            real_file_sha256 = package_integrity.file_sha256

            def reject_source_prehash(path):
                if Path(path).resolve() == source.resolve():
                    raise AssertionError("source was hashed in a separate pre-write pass")
                return real_file_sha256(path)

            with patch(
                "scripts.package_integrity.file_sha256",
                side_effect=reject_source_prehash,
            ):
                result = write_verified_archive(
                    root,
                    output,
                    [source],
                    release,
                    "single-source-pass-test",
                )

            self.assertEqual(result["file_count"], 1)
            self.assertTrue(output.is_file())

    def test_concurrent_writer_for_same_output_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            output = Path(temp) / "release.zip"
            with exclusive_output_lock(output):
                with self.assertRaisesRegex(RuntimeError, "already being written"):
                    with exclusive_output_lock(output):
                        self.fail("second writer acquired the same output lock")
            self.assertFalse((Path(temp) / ".release.zip.lock").exists())

    def test_duplicate_symlink_and_output_inputs_are_rejected(self) -> None:
        release = {
            "release_id": "test-audit49",
            "generated_at": "2026-07-26T18:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source.txt"
            source.write_text("source\n", encoding="utf-8")
            output = root / "release.zip"
            with self.assertRaisesRegex(ValueError, "duplicate archive member"):
                write_verified_archive(root, output, [source, source], release, "test")
            output.write_bytes(b"prior output")
            with self.assertRaisesRegex(ValueError, "transaction artifact"):
                write_verified_archive(root, output, [output], release, "test")
            link = root / "source-link.txt"
            try:
                link.symlink_to(source)
            except (OSError, NotImplementedError):
                return
            with self.assertRaisesRegex(ValueError, "symbolic link"):
                write_verified_archive(root, output, [link], release, "test")

    def test_streamed_member_verification_detects_crc_corruption(self) -> None:
        payload = b"crc-protected-content\n"
        row = {
            "path": "alpha.txt",
            "bytes": len(payload),
            "sha256": hashlib.sha256(payload).hexdigest(),
        }
        with tempfile.TemporaryDirectory() as temp:
            archive_path = Path(temp) / "corrupt.zip"
            with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_STORED) as archive:
                archive.writestr(row["path"], payload)
            with zipfile.ZipFile(archive_path) as archive:
                info = archive.getinfo(row["path"])
            data_offset = (
                info.header_offset
                + 30
                + len(info.filename.encode("utf-8"))
                + len(info.extra)
            )
            with archive_path.open("r+b") as handle:
                handle.seek(data_offset)
                first_byte = handle.read(1)
                handle.seek(data_offset)
                handle.write(bytes([first_byte[0] ^ 0x01]))

            with zipfile.ZipFile(archive_path) as archive:
                with self.assertRaisesRegex(RuntimeError, "CRC verification failed"):
                    verify_file_member(archive, row)

    def test_failed_write_preserves_prior_verified_artifact(self) -> None:
        release = {
            "release_id": "test-audit36",
            "generated_at": "2026-07-24T20:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "alpha.txt"
            source.write_text("alpha\n", encoding="utf-8")
            output = root / "release.zip"
            sidecar = Path(str(output) + ".sha256")
            output.write_bytes(b"prior-verified-archive")
            sidecar.write_text("prior-digest  release.zip\n", encoding="utf-8")

            with patch("scripts.package_integrity.zipfile.ZipFile", side_effect=RuntimeError("synthetic write failure")):
                with self.assertRaisesRegex(RuntimeError, "synthetic write failure"):
                    write_verified_archive(root, output, [source], release, "test")

            self.assertEqual(output.read_bytes(), b"prior-verified-archive")
            self.assertEqual(sidecar.read_text(encoding="utf-8"), "prior-digest  release.zip\n")
            self.assertEqual(list(root.glob(".*.part-*")), [])

    def test_failed_sidecar_commit_restores_prior_verified_pair(self) -> None:
        release = {
            "release_id": "test-audit36",
            "generated_at": "2026-07-24T20:00:00-04:00",
        }
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "alpha.txt"
            source.write_text("new archive contents\n", encoding="utf-8")
            output = root / "release.zip"
            sidecar = Path(str(output) + ".sha256")
            prior_archive = b"prior-verified-archive"
            prior_sidecar = "prior-digest  release.zip\n"
            output.write_bytes(prior_archive)
            sidecar.write_text(prior_sidecar, encoding="utf-8")
            real_replace = os.replace
            failed_once = False

            def fail_new_sidecar_once(source_path, target_path):
                nonlocal failed_once
                source_value = Path(source_path)
                target_value = Path(target_path)
                if (
                    not failed_once
                    and ".part-" in source_value.name
                    and target_value == sidecar
                ):
                    failed_once = True
                    raise OSError("synthetic sidecar commit failure")
                return real_replace(source_path, target_path)

            with patch("scripts.package_integrity.os.replace", side_effect=fail_new_sidecar_once):
                with self.assertRaisesRegex(OSError, "synthetic sidecar commit failure"):
                    write_verified_archive(root, output, [source], release, "test")

            self.assertTrue(failed_once)
            self.assertEqual(output.read_bytes(), prior_archive)
            self.assertEqual(sidecar.read_text(encoding="utf-8"), prior_sidecar)
            self.assertEqual(list(root.glob(".*.part-*")), [])
            self.assertEqual(list(root.glob(".*.previous")), [])


class PackageSelectionTests(unittest.TestCase):
    def test_selector_prunes_mixed_case_detienne_recovery_duplicates(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            output = root / "release.zip"
            canonical = (
                root
                / "UPDATE_SOURCES"
                / "DETIENNE_CHAPTER_LEDGERS_2026-08-27"
                / "README.md"
            )
            canonical.parent.mkdir(parents=True)
            canonical.write_text("canonical\n", encoding="utf-8")
            duplicate_paths = (
                root
                / "UPDATE_SOURCES"
                / "Detienne_Comparing_the_Incomparable_Polymyth_Master_Notes_2026-08-27.md",
                root
                / "UPDATE_SOURCES"
                / "Detienne_Evidence_Ledgers_2026-08-27"
                / "README.md",
                root
                / "SITE_PACKAGE"
                / "UPDATE_SOURCES"
                / "Detienne_Comparing_the_Incomparable_Polymyth_Master_Notes_2026-08-27.md",
                root
                / "SITE_PACKAGE"
                / "UPDATE_SOURCES"
                / "Detienne_Evidence_Ledgers_2026-08-27"
                / "detienne_ch2.md",
            )
            for duplicate in duplicate_paths:
                duplicate.parent.mkdir(parents=True, exist_ok=True)
                duplicate.write_text("transient duplicate\n", encoding="utf-8")

            files, stats = collect_package_files(root, output)
            selected = [path.relative_to(root).as_posix() for path in files]

            self.assertEqual(
                selected,
                ["UPDATE_SOURCES/DETIENNE_CHAPTER_LEDGERS_2026-08-27/README.md"],
            )
            self.assertEqual(stats["reconstruction_duplicates_pruned"], 4)
            for duplicate in duplicate_paths:
                self.assertTrue(
                    is_reconstruction_duplicate(duplicate.relative_to(root).as_posix())
                )

    def test_generated_report_byte_metric_is_status_independent(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            output = root / "release.zip"
            content = root / "content.txt"
            audit49_report = root / "audit49-build-packaging-efficiency.json"
            technical_report = root / "audit49-technical-efficiency.json"
            release_report = root / "release-gate-report.json"
            futureproof_report = root / "futureproofing-gate-report.json"
            content.write_bytes(b"durable-content")
            audit49_report.write_bytes(b"self-updating-audit49")
            technical_report.write_bytes(b"self-updating-aggregate")
            release_report.write_bytes(b'{"status":"failed","details":[1,2,3]}')
            futureproof_report.write_bytes(b'{"status":"failed"}')
            files, _ = collect_package_files(root, output)
            excluded = (
                audit49_report,
                technical_report,
                release_report,
                futureproof_report,
            )
            before = selected_bytes_excluding(files, excluded)

            release_report.write_bytes(b'{"status":"passed"}')
            audit49_report.write_bytes(b"different-self-report-size")
            technical_report.write_bytes(b"different-aggregate-size-and-content")
            futureproof_report.write_bytes(b'{"status":"passed","checks":12}')
            after = selected_bytes_excluding(files, excluded)

            self.assertEqual(before, len(b"durable-content"))
            self.assertEqual(after, before)

    def test_selector_prunes_root_abandoned_public_build_only(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            output = root / "release.zip"
            abandoned = root / ".ss-public-build-abandoned-manual-fixture" / "staging"
            abandoned.mkdir(parents=True)
            (abandoned / "index.html").write_text("stale public build\n", encoding="utf-8")
            nested = (
                root
                / "data"
                / ".ss-public-build-abandoned-preserved-evidence"
                / "evidence.json"
            )
            nested.parent.mkdir(parents=True)
            nested.write_text("{}\n", encoding="utf-8")

            files, stats = collect_package_files(root, output)
            selected = [path.relative_to(root).as_posix() for path in files]

            self.assertEqual(
                selected,
                ["data/.ss-public-build-abandoned-preserved-evidence/evidence.json"],
            )
            self.assertEqual(stats["directories_pruned"], 1)

    def test_selector_prunes_disposable_trees_and_preserves_nested_evidence(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            output = root / "ss-site-audit49-final.zip"
            (root / "keep.txt").write_text("keep\n", encoding="utf-8")
            (root / ".env.example").write_text("EXAMPLE=1\n", encoding="utf-8")
            (root / ".env.local").write_text("PRIVATE=1\n", encoding="utf-8")
            (root / "ignored.log").write_text("log\n", encoding="utf-8")
            (root / "node_modules" / "deep").mkdir(parents=True)
            for index in range(20):
                (root / "node_modules" / "deep" / f"{index}.js").write_text(
                    "dependency\n",
                    encoding="utf-8",
                )
            (root / ".venv-audit" / "lib").mkdir(parents=True)
            (root / ".venv-audit" / "lib" / "module.py").write_text(
                "dependency\n",
                encoding="utf-8",
            )
            (root / "audit49-work").mkdir()
            (root / "audit49-work" / "temporary.txt").write_text(
                "temporary\n",
                encoding="utf-8",
            )
            (root / ".seminar-schools-build.lock").mkdir()
            (root / ".seminar-schools-build.lock" / "owner.json").write_text(
                '{"token":"transient"}\n',
                encoding="utf-8",
            )
            (root / ".seminar-schools-build.lease").write_text(
                "stable advisory-lock inode; never package\n",
                encoding="utf-8",
            )
            for transient_name in (
                ".cache",
                "cache",
                ".locks",
                "locks",
                ".logs",
                "logs",
                ".log",
                "log",
                ".staging",
                "staging",
                ".temp",
                "temp",
                ".tmp",
                "tmp",
                "__pycache__",
                "custom-build.lock",
            ):
                transient = root / transient_name
                transient.mkdir()
                (transient / "discard.txt").write_text(
                    "transient\n",
                    encoding="utf-8",
                )
            (root / "discard.pyc").write_bytes(b"python bytecode")
            nested_lease = root / "SITE_PACKAGE" / ".seminar-schools-build.lease"
            nested_lease.parent.mkdir(parents=True)
            nested_lease.write_text(
                "nested advisory-lock inode; never package\n",
                encoding="utf-8",
            )
            (root / "data" / "polymythcal-audit35").mkdir(parents=True)
            (root / "data" / "polymythcal-audit35" / "evidence.json").write_text(
                "{}\n",
                encoding="utf-8",
            )
            (root / "public").mkdir()
            (root / "public" / "index.html").write_text("public\n", encoding="utf-8")
            (root / "downloads").mkdir()
            (root / "downloads" / "lesson.zip").write_bytes(b"intentional download")
            for tombstone in (
                ".public-build-lock",
                ".public-build-staging",
                ".public-build-previous",
            ):
                (root / tombstone).write_text(
                    '{"schema":"seminar-schools-public-build-overlay-tombstone-v1"}\n',
                    encoding="utf-8",
                )
            output.write_bytes(b"prior package")
            Path(str(output) + ".sha256").write_text("prior digest\n", encoding="utf-8")
            (root / ".ss-site-audit49-final.zip.part-123").write_bytes(b"partial")
            for suffix in (
                ".audit-receipt.json",
                ".clean-room-report.json",
                ".disaster-recovery-report.json",
            ):
                (root / f"ss-site-prior.zip{suffix}").write_text("{}\n", encoding="utf-8")

            files, stats = collect_package_files(
                root,
                output,
                excluded_top_level={"public"},
            )
            selected = [path.relative_to(root).as_posix() for path in files]

            self.assertEqual(
                selected,
                [
                    ".env.example",
                    "data/polymythcal-audit35/evidence.json",
                    "downloads/lesson.zip",
                    "keep.txt",
                ],
            )
            self.assertEqual(stats["files_selected"], 4)
            self.assertGreaterEqual(stats["directories_pruned"], 5)
            # Three sibling release-evidence fixtures and three exact overlay
            # tombstones are considered and deliberately excluded in addition
            # to the original selection set.
            self.assertLessEqual(stats["files_considered"], 18)


if __name__ == "__main__":
    unittest.main()
