#!/usr/bin/env python3
"""Require the primary package to match an independent clean-copy rebuild."""
from __future__ import annotations

import argparse
from datetime import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile

from clean_room_copy import copy_clean_source
from atomic_json import write_json_atomic
from audit_python_dependencies import (
    installed_distribution_inventory,
    pinned_audit_requirements_evidence,
)
from build_lock import require_release_build_lock


SITE_ROOT = Path(__file__).resolve().parents[1]
DELIVERY_ROOT = SITE_ROOT.parent
DEFAULT_REPORT = SITE_ROOT / "scripts/reports/clean-room-release-report.json"
CHUNK = 1024 * 1024
PIPELINE_ID = "npm-ci-build-full-verify-editable-package-v1"
COMPARE_PIPELINE_ID = "archive-pair-comparison-v1"
REPORT_SCHEMA = "seminar-schools-clean-room-release-report-v1"
GENERATED_MANIFEST_PATHS = {
    "PACKAGE_CONTENTS_SHA256.json",
    "SITE_PACKAGE/PACKAGE_CONTENTS_SHA256.json",
}
PIPELINE_HELPERS = (
    "SITE_PACKAGE/scripts/clean_room_copy.py",
    "SITE_PACKAGE/scripts/build_lock.py",
    "SITE_PACKAGE/scripts/run-with-build-lock.py",
    "SITE_PACKAGE/scripts/build-clean-room-release.py",
    "SITE_PACKAGE/scripts/editable_masters_integrity.py",
    "SITE_PACKAGE/scripts/package-front-facing-mephistodata-release.py",
    "SITE_PACKAGE/scripts/package_integrity.py",
    "SITE_PACKAGE/scripts/package_selection.py",
    "SITE_PACKAGE/scripts/audit_python_dependencies.py",
)
INHERITED_ENVIRONMENT_ALLOWLIST = (
    "PATH",
    "SystemRoot",
    "WINDIR",
    "COMSPEC",
    "PATHEXT",
    "CHROME_EXECUTABLE",
    "CHROME_PATH",
    "CHROMIUM_PATH",
    "PUPPETEER_EXECUTABLE_PATH",
    "PLAYWRIGHT_BROWSERS_PATH",
    "HTTP_PROXY",
    "HTTPS_PROXY",
    "NO_PROXY",
    "ALL_PROXY",
    "http_proxy",
    "https_proxy",
    "no_proxy",
    "all_proxy",
    "NPM_CONFIG_REGISTRY",
    "NPM_CONFIG_OFFLINE",
    "NPM_CONFIG_PROXY",
    "NPM_CONFIG_HTTPS_PROXY",
    "NPM_CONFIG_HTTP_PROXY",
    "NPM_CONFIG_NOPROXY",
    "NODE_EXTRA_CA_CERTS",
    "SSL_CERT_FILE",
    "SSL_CERT_DIR",
    "NODE_USE_ENV_PROXY",
    "PIP_NO_INDEX",
    "PIP_FIND_LINKS",
)


def sidecar_binds(sidecar: Path, archive: Path, digest: str) -> bool:
    try:
        text = sidecar.read_text(encoding="utf-8")
    except OSError:
        return False
    match = re.fullmatch(r"([a-f0-9]{64})  ([^\r\n]+)\r?\n?", text)
    return bool(match and match.group(1) == digest and match.group(2) == archive.name)


def embedded_manifest(path: Path) -> dict:
    with zipfile.ZipFile(path, "r") as archive:
        payload = archive.read("PACKAGE_CONTENTS_SHA256.json")
    value = json.loads(payload)
    return {
        "sha256": hashlib.sha256(payload).hexdigest(),
        "schema": value.get("schema"),
        "package_kind": value.get("package_kind"),
        "release_id": value.get("release_id"),
        "generated_at": value.get("generated_at"),
        "file_count": value.get("file_count"),
    }


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(CHUNK), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def release_metadata(reference_archive: Path) -> tuple[str, str]:
    manifest = embedded_manifest(reference_archive)
    release_id = manifest.get("release_id")
    generated_at = manifest.get("generated_at")
    if not isinstance(release_id, str) or not release_id.strip():
        raise ValueError("reference archive embedded manifest lacks a release_id")
    if not isinstance(generated_at, str) or not generated_at.strip():
        raise ValueError("reference archive embedded manifest lacks generated_at")
    try:
        stamp = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError("reference archive generated_at is not ISO-8601") from error
    if stamp.tzinfo is None:
        raise ValueError("reference archive generated_at must include a timezone")
    return release_id, generated_at


def generated_at_epoch(generated_at: str) -> str:
    stamp = datetime.fromisoformat(generated_at.replace("Z", "+00:00"))
    if stamp.tzinfo is None:
        raise ValueError("generated_at must include a timezone")
    return str(int(stamp.timestamp()))


def source_tree_evidence(root: Path) -> dict:
    """Hash the canonical rebuild inputs before any build runs.

    The two package manifests are regenerated by packaging and are therefore
    excluded from both this digest and the independently derived ZIP digest.
    """
    rows: list[tuple[str, int, str]] = []
    total_bytes = 0
    for current, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        symlinked_directories = [
            name for name in directory_names if (current_path / name).is_symlink()
        ]
        if symlinked_directories:
            raise ValueError(
                "clean source snapshot contains directory symlinks: "
                + ", ".join(sorted(symlinked_directories))
            )
        directory_names[:] = sorted(directory_names)
        for name in sorted(file_names):
            candidate = current_path / name
            if candidate.is_symlink() or not candidate.is_file():
                raise ValueError(f"clean source snapshot contains a non-regular file: {candidate}")
            relative = candidate.relative_to(root).as_posix()
            if relative in GENERATED_MANIFEST_PATHS:
                continue
            size = candidate.stat().st_size
            rows.append((relative, size, sha256(candidate)))
            total_bytes += size
    digest = hashlib.sha256()
    # os.walk() is depth-first, while package manifests are globally sorted by
    # archive path. Canonicalize both evidence streams to the same ordering so
    # identical trees cannot fail merely because nested paths were visited at
    # different times.
    for relative, size, file_digest in sorted(rows, key=lambda value: value[0]):
        digest.update(f"{relative}\0{size}\0{file_digest}\n".encode("utf-8"))
    return {
        "tree_sha256": digest.hexdigest(),
        "file_count": len(rows),
        "total_bytes": total_bytes,
        "excluded_generated_manifests": sorted(GENERATED_MANIFEST_PATHS),
    }


def archive_rebuild_input_evidence(path: Path) -> dict:
    """Derive the same prebuild-input digest independently from a final ZIP."""
    with zipfile.ZipFile(path, "r") as archive:
        manifest = json.loads(archive.read("PACKAGE_CONTENTS_SHA256.json"))
    rows = [
        row for row in (manifest.get("files") or [])
        if row.get("path") not in GENERATED_MANIFEST_PATHS
    ]
    digest = hashlib.sha256()
    total_bytes = 0
    for row in sorted(rows, key=lambda value: str(value.get("path") or "")):
        relative = str(row.get("path") or "")
        size = row.get("bytes")
        file_digest = str(row.get("sha256") or "")
        if type(size) is not int or size < 0 or not re.fullmatch(r"[a-f0-9]{64}", file_digest):
            raise ValueError(f"final archive has malformed rebuild-input evidence: {relative}")
        digest.update(f"{relative}\0{size}\0{file_digest}\n".encode("utf-8"))
        total_bytes += size
    return {
        "tree_sha256": digest.hexdigest(),
        "file_count": len(rows),
        "total_bytes": total_bytes,
        "excluded_generated_manifests": sorted(GENERATED_MANIFEST_PATHS),
    }


def helper_evidence(clean_root: Path) -> list[dict]:
    rows: list[dict] = []
    for relative in PIPELINE_HELPERS:
        helper = clean_root / relative
        trusted_helper = DELIVERY_ROOT / relative
        if not helper.is_file() or helper.is_symlink():
            raise ValueError(f"canonical clean-room helper is missing: {relative}")
        if not trusted_helper.is_file() or trusted_helper.is_symlink():
            raise ValueError(f"trusted canonical helper is missing: {relative}")
        actual_digest = sha256(helper)
        trusted_digest = sha256(trusted_helper)
        if actual_digest != trusted_digest:
            raise ValueError(f"clean source snapshot substituted canonical helper: {relative}")
        rows.append(
            {
                "path": relative,
                "bytes": helper.stat().st_size,
                "sha256": actual_digest,
                "trusted_sha256": trusted_digest,
                "matches_trusted_helper": True,
            }
        )
    return rows


def executable_input_evidence(environment: dict[str, str]) -> list[dict]:
    """Hash executable files that can materially affect the clean rebuild."""
    candidates = {
        "python": sys.executable,
        "node": shutil.which("node", path=environment.get("PATH")),
        "npm": shutil.which("npm.cmd" if os.name == "nt" else "npm", path=environment.get("PATH")),
        **{
            key: environment.get(key)
            for key in (
                "CHROME_EXECUTABLE",
                "CHROME_PATH",
                "CHROMIUM_PATH",
                "PUPPETEER_EXECUTABLE_PATH",
            )
            if environment.get(key)
        },
    }
    missing_mandatory = [name for name in ("python", "node", "npm") if not candidates.get(name)]
    if missing_mandatory:
        raise ValueError(
            "clean-room environment cannot resolve mandatory executables: "
            + ", ".join(missing_mandatory)
        )
    rows: list[dict] = []
    for name, configured_path in sorted(candidates.items()):
        if not configured_path:
            continue
        candidate = Path(configured_path).expanduser()
        row = {"name": name, "configured_path": str(configured_path)}
        if candidate.is_file():
            resolved = candidate.resolve()
            row.update(
                {
                    "resolved_path": str(resolved),
                    "bytes": resolved.stat().st_size,
                    "sha256": sha256(resolved),
                    "clean_room_host_attested": True,
                }
            )
        else:
            raise ValueError(f"clean-room executable is not a regular file: {name}")
        rows.append(row)
    return rows


def canonical_pipeline_steps(release_id: str, generated_at: str) -> list[dict]:
    """Describe the fixed, shell-free pipeline whose helpers are hashed."""
    return [
        {
            "order": 1,
            "action": "copy_clean_source",
            "implementation": "SITE_PACKAGE/scripts/clean_room_copy.py",
        },
        {
            "order": 2,
            "action": "run_locked_build_helper",
            "argv": [
                "{python}",
                "SITE_PACKAGE/scripts/run-with-build-lock.py",
                "--delivery-root",
                "{clean_delivery_root}",
                "--",
                "{python}",
                "SITE_PACKAGE/scripts/build-clean-room-release.py",
                "{output_zip}",
                "--release-id",
                release_id,
                "--generated-at",
                generated_at,
            ],
        },
        {
            "order": 3,
            "action": "install_pinned_python_audit_dependencies",
            "implementation": "SITE_PACKAGE/scripts/audit_python_dependencies.py",
            "top_level_requirements": "SITE_PACKAGE/requirements-audit.txt",
            "resolved_lock": "SITE_PACKAGE/requirements-audit.lock",
            "target": "{isolated_python_audit_target}",
            "argv": [
                "{python}",
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                "--no-input",
                "--require-hashes",
                "--target",
                "{isolated_python_audit_target}",
                "-r",
                "SITE_PACKAGE/requirements-audit.lock",
            ],
        },
        {"order": 4, "action": "npm_clean_install", "argv": ["npm", "ci"]},
        {"order": 5, "action": "canonical_build", "argv": ["npm", "run", "build"]},
        {
            "order": 6,
            "action": "full_built_tree_verification",
            "argv": ["npm", "run", "verify:all:built"],
        },
        {
            "order": 7,
            "action": "verify_editable_masters",
            "implementation": "SITE_PACKAGE/scripts/editable_masters_integrity.py",
        },
        {
            "order": 8,
            "action": "package_complete_release",
            "argv": [
                "{python}",
                "SITE_PACKAGE/scripts/package-front-facing-mephistodata-release.py",
                "{output_zip}",
                "--release-id",
                release_id,
                "--generated-at",
                generated_at,
            ],
        },
    ]


def clean_environment(environment_root: Path, generated_at: str) -> tuple[dict[str, str], dict]:
    """Create and document the canonical minimal subprocess environment."""
    home = environment_root / "home"
    temporary = environment_root / "tmp"
    npm_cache = environment_root / "npm-cache"
    for directory in (home, temporary, npm_cache):
        directory.mkdir(parents=True, exist_ok=True)
    npm_user_config = environment_root / "empty-npmrc"
    npm_user_config.write_text("", encoding="utf-8")

    inherited = {
        key: os.environ[key]
        for key in INHERITED_ENVIRONMENT_ALLOWLIST
        if os.environ.get(key)
    }
    environment = dict(inherited)
    environment.setdefault("PATH", os.defpath)
    environment.update(
        {
            "HOME": str(home),
            "USERPROFILE": str(home),
            "TMPDIR": str(temporary),
            "TMP": str(temporary),
            "TEMP": str(temporary),
            "TZ": "UTC",
            "LC_ALL": "C",
            "LANG": "C",
            "PYTHONHASHSEED": "0",
            "SOURCE_DATE_EPOCH": generated_at_epoch(generated_at),
            "SS_PUBLIC_OUTPUT_MTIME": generated_at,
            "CI": "1",
            "NPM_CONFIG_USERCONFIG": str(npm_user_config),
            "NPM_CONFIG_CACHE": str(npm_cache),
            "NPM_CONFIG_AUDIT": "false",
            "NPM_CONFIG_FUND": "false",
            "NPM_CONFIG_UPDATE_NOTIFIER": "false",
            "VERIFY_ALL_CONCURRENCY": "4",
            "VERIFY_ALL_COMMAND_TIMEOUT_MS": "2700000",
            "SS_CLEAN_ROOM_CANONICAL_PIPELINE": PIPELINE_ID,
        }
    )
    inherited_fingerprints = {
        key: {"bytes": len(value.encode("utf-8")), "sha256": sha256_text(value)}
        for key, value in sorted(inherited.items())
    }
    evidence = {
        "allowlisted_inherited_names": list(INHERITED_ENVIRONMENT_ALLOWLIST),
        "inherited_value_fingerprints": inherited_fingerprints,
        "fixed_values": {
            "TZ": "UTC",
            "LC_ALL": "C",
            "LANG": "C",
            "PYTHONHASHSEED": "0",
            "SOURCE_DATE_EPOCH": environment["SOURCE_DATE_EPOCH"],
            "SS_PUBLIC_OUTPUT_MTIME": environment["SS_PUBLIC_OUTPUT_MTIME"],
            "CI": "1",
            "NPM_CONFIG_AUDIT": "false",
            "NPM_CONFIG_FUND": "false",
            "NPM_CONFIG_UPDATE_NOTIFIER": "false",
            "VERIFY_ALL_CONCURRENCY": "4",
            "VERIFY_ALL_COMMAND_TIMEOUT_MS": "2700000",
            "SS_CLEAN_ROOM_CANONICAL_PIPELINE": PIPELINE_ID,
        },
        "isolated_paths": [
            "HOME",
            "USERPROFILE",
            "TMPDIR",
            "TMP",
            "TEMP",
            "NPM_CONFIG_USERCONFIG",
            "NPM_CONFIG_CACHE",
        ],
        "python": {
            "executable": sys.executable,
            "version": sys.version.split()[0],
        },
        "executable_files": executable_input_evidence(environment),
    }
    return environment, evidence


def compare_archive_pair(left: Path, right: Path) -> tuple[list[str], dict]:
    failures: list[str] = []
    left = Path(left)
    right = Path(right)
    left_sidecar = Path(str(left) + ".sha256")
    right_sidecar = Path(str(right) + ".sha256")
    for path in (left, right, left_sidecar, right_sidecar):
        if not path.is_file():
            failures.append(f"reproducibility artifact is missing: {path}")
    if failures:
        return failures, {}
    left_digest = sha256(left)
    right_digest = sha256(right)
    byte_identical = left.stat().st_size == right.stat().st_size and left_digest == right_digest
    sidecar_identical = sidecar_binds(left_sidecar, left, left_digest) and sidecar_binds(
        right_sidecar, right, right_digest
    )
    try:
        left_manifest = embedded_manifest(left)
        right_manifest = embedded_manifest(right)
        manifest_identical = left_manifest == right_manifest
    except (OSError, KeyError, ValueError, zipfile.BadZipFile) as error:
        left_manifest = {}
        right_manifest = {}
        manifest_identical = False
        failures.append(f"clean-room embedded manifest could not be verified: {error}")
    if not byte_identical:
        failures.append("clean-room archives are not byte-identical")
    if not sidecar_identical:
        failures.append("one or both clean-room checksum sidecars do not bind to their archive")
    if not manifest_identical:
        failures.append("clean-room embedded manifests are not identical")
    return failures, {
        "left": {"bytes": left.stat().st_size, "sha256": left_digest},
        "right": {"bytes": right.stat().st_size, "sha256": right_digest},
        "byte_identical": byte_identical,
        "sidecar_identical": sidecar_identical,
        "manifest_identical": manifest_identical,
        "left_manifest": left_manifest,
        "right_manifest": right_manifest,
    }


def materialize_and_run(
    source_root: Path,
    destination: Path,
    label: str,
    release_id: str,
    generated_at: str,
) -> tuple[Path, dict]:
    """Run the one canonical clean-room pipeline; no caller command is accepted."""
    clean_root = destination / label
    copy_clean_source(source_root, clean_root)
    snapshot = source_tree_evidence(clean_root)
    helpers = helper_evidence(clean_root)
    pinned_python_dependencies = pinned_audit_requirements_evidence(
        clean_root / "SITE_PACKAGE"
    )
    output = clean_root / "ss-site-clean-room.zip"
    environment, environment_evidence = clean_environment(
        destination / f"{label}-external-inputs", generated_at
    )
    run_with_lock = clean_root / "SITE_PACKAGE/scripts/run-with-build-lock.py"
    build_helper = clean_root / "SITE_PACKAGE/scripts/build-clean-room-release.py"
    command = [
        sys.executable,
        str(run_with_lock),
        "--delivery-root",
        str(clean_root),
        "--",
        sys.executable,
        str(build_helper),
        str(output),
        "--release-id",
        release_id,
        "--generated-at",
        generated_at,
    ]
    subprocess.run(command, cwd=clean_root / "SITE_PACKAGE", env=environment, check=True)
    installed_inventory = installed_distribution_inventory(
        Path(environment["TMPDIR"]) / "seminar-schools-python-audit-deps"
    )
    if installed_inventory != pinned_python_dependencies["locked_distributions"]:
        raise ValueError(
            "installed clean-room Python audit inventory differs from its resolved lock"
        )
    pinned_python_dependencies.update(
        {
            "installed_distribution_count": len(installed_inventory),
            "installed_distributions": installed_inventory,
            "installed_inventory_matches_lock": True,
        }
    )
    return output, {
        "source_snapshot": snapshot,
        "pipeline_helpers": helpers,
        "pipeline_steps": canonical_pipeline_steps(release_id, generated_at),
        "pinned_python_audit_dependencies": pinned_python_dependencies,
        "pinned_python_audit_dependencies_verified": True,
        "external_inputs": environment_evidence,
    }


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compare", nargs=2, type=Path, metavar=("LEFT_ZIP", "RIGHT_ZIP"))
    parser.add_argument("--reference-archive", type=Path)
    parser.add_argument("--source-root", type=Path, default=DELIVERY_ROOT)
    parser.add_argument("--delivery-root", type=Path, default=DELIVERY_ROOT)
    parser.add_argument(
        "--command-json",
        help="retired and forbidden; the canonical reference pipeline is verifier-owned",
    )
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument(
        "--pipeline-id",
        help="retired and forbidden; mode-specific pipeline identity is verifier-owned",
    )
    args = parser.parse_args(argv)
    if args.command_json is not None:
        parser.error("--command-json is forbidden; the verifier constructs the fixed pipeline")
    if args.pipeline_id is not None:
        parser.error("--pipeline-id is verifier-owned and cannot be supplied by a caller")
    if args.compare and args.reference_archive:
        parser.error("use either --compare or --reference-archive, not both")
    if not args.compare and not args.reference_archive:
        parser.error("use --compare or --reference-archive")
    require_release_build_lock(args.delivery_root)

    if args.compare:
        left, right = args.compare
        failures, evidence = compare_archive_pair(left, right)
        mode_evidence = {
            "mode": "compare_only",
            "canonical_pipeline": False,
            "pipeline_id": COMPARE_PIPELINE_ID,
            "pipeline_steps": [
                {
                    "order": 1,
                    "action": "compare_caller_supplied_archives",
                    "canonical_rebuild_executed": False,
                }
            ],
        }
    else:
        reference = args.reference_archive.resolve()
        try:
            release_id, generated_at = release_metadata(reference)
        except (OSError, KeyError, ValueError, zipfile.BadZipFile) as error:
            parser.error(str(error))
        with tempfile.TemporaryDirectory(prefix="ss-clean-room-release-") as temporary:
            root = Path(temporary)
            left = reference
            right, rebuild_evidence = materialize_and_run(
                args.source_root.resolve(),
                root,
                "clean-rebuild",
                release_id,
                generated_at,
            )
            failures, evidence = compare_archive_pair(left, right)
            archive_inputs = archive_rebuild_input_evidence(right)
            snapshot_matches_archive = rebuild_evidence["source_snapshot"] == archive_inputs
            if not snapshot_matches_archive:
                failures.append(
                    "clean-room prebuild snapshot differs from the final archive rebuild inputs"
                )
        mode_evidence = {
            "mode": "reference_rebuild",
            "canonical_pipeline": True,
            "pipeline_id": PIPELINE_ID,
            "release_id": release_id,
            "generated_at": generated_at,
            "source_snapshot_matches_archive": snapshot_matches_archive,
            "archive_rebuild_inputs": archive_inputs,
            **rebuild_evidence,
        }

    check_fields = ["byte_identical", "sidecar_identical", "manifest_identical"]
    if not args.compare:
        check_fields.append("source_snapshot_matches_archive")
        check_fields.append("pinned_python_audit_dependencies_verified")
    result_flags = {**evidence, **mode_evidence}
    report = {
        "schema": REPORT_SCHEMA,
        "status": "failed" if failures else "passed",
        "total_checks": len(check_fields),
        "passed_checks": sum(
            int(result_flags.get(field) is True)
            for field in check_fields
        ),
        "failed_checks": failures,
        **mode_evidence,
        **evidence,
    }
    write_json_atomic(args.report, report)
    if failures:
        print("CLEAN-ROOM REPRODUCIBILITY FAILED")
        for failure in failures:
            print(f" - {failure}")
        raise SystemExit(1)
    print(f"CLEAN-ROOM REPRODUCIBILITY PASSED — both archives are {evidence['left']['sha256']}.")


if __name__ == "__main__":
    main()
